### ISSUE TITLE
triton implementation seems not to work for dim == 128 with A40s

### ISSUE THREAD

**Issue by jkobject** [Dao-AILab/flash-attention#1006]
I am using the triton implementation for multiple reasons and ease of use.

I am using all the right packages and work on A40s.
It runs well on dim 64 and 32.

But I get an error on the backward pass for 128 

```
....
  File "/pasteur/appa/homes/jkalfon/scPRINT/scprint/model/model.py", l
ine 1014, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/core/optimizer.py", line 152, i
n step
    step_output = self._strategy.optimizer_step(self._optimizer, closu
re, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/strategies/ddp.py", line 270, i
n optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, mode
l, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 2
39, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model
, closure=closure, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/plugins/precision/amp.py", line
 80, in optimizer_step
    closure_result = closure()
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py
", line 144, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorat
e_context
    return func(*args, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py
", line 138, in closure
    self._backward_fn(step_output.closure_loss)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py
", line 240, in backward_fn
    call._call_strategy_hook(self.trainer, "backward", loss, optimizer
)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/trainer/call.py", line 309, in 
_call_strategy_hook
    output = fn(*args, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 2
13, in backward
    self.precision_plugin.backward(closure_loss, self.lightning_module
, optimizer, *args, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/plugins/precision/precision.py"
, line 72, in backward
    model.backward(tensor, *args, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/lightning/pytorch/core/module.py", line 1090, in 
backward
    loss.backward(*args, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/torch/autograd/__init__.py", line 200, in backwar
d
    Variable._execution_engine.run_backward(  # Calls into the C++ eng
ine to run the backward pass
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/pyth
on3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/pasteur/appa/homes/jkalfon/scPRINT/scprint/model/flash_attn/f
lashattention.py", line 1107, in backward
    _flash_attn_backward(
  File "/pasteur/appa/homes/jkalfon/scPRINT/scprint/model/flash_attn/f
lashattention.py", line 1021, in _flash_attn_backward 
    _bwd_kernel[grid](
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/python3.10/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 73, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 73, in <dictcomp> 
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 63, in _bench
    return do_bench(kernel_call)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/python3.10/site-packages/triton/testing.py", line 140, in do_bench
    fn()
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 62, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "/pasteur/appa/homes/jkalfon/miniconda3/envs/scprint17/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 200, in run
    return self.fn.run(*args, **kwargs)
  File "<string>", line 43, in _bwd_kernel
RuntimeError: Triton Error [CUDA]: invalid argument
Traceback (most recent call last):
  File "<string>", line 21, in _bwd_kernel
KeyError: ('2-.-0-.-0-7d1eb0d2fed8ff2032dccb99c2cc311a-2b0c5161c53c71b
37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-d962222789c30252d49
2a16cca3bf467-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca
29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9
dfa59-d35ab04ae841e2714a253c523530b071', (torch.float16, torch.float16
, torch.float16, None, torch.float16, torch.float32, torch.float16, to
rch.float16, torch.float32, torch.float32, 'fp32', 'i32', 'i32', 'i32'
, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'
, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'
, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), ('none', Fa
lse, 128, False, False, False, True, 128, 128), (True, True, True, (Fa
lse,), True, True, True, True, True, True, (False,), (True, False), (T
rue, False), (True, False), (True, False), (True, False), (True, False
), (True, False), (True, False), (True, False), (True, False), (True, 
False), (True, False), (True, False), (True, False), (True, False), (T
rue, False), (True, False), (True, False), (True, False), (True, False
), (True, False), (True, False), (True, False), (True, False), (False,
 False), (True, False), (True, False), (True, False), (True, False), (
False, False), (False, False)))
```

using :
triton                    2.0.0.dev20221202
torch                     2.0.0
lightning               2.2.0.post0
cuda 11.7

**Comment by tridao** [comment]
You should try the implementation in the triton repo: https://github.com/triton-lang/triton/blob/main/python/tutorials/06-fused-attention.py

**Comment by jkobject** [comment]
Ok I will. Do you have a reason to think it should be more compatible than your updated one?
Thanks btw! :)

**Comment by tridao** [comment]
The version in triton repo is much better maintained :D
