### ISSUE TITLE
flash-attn 1.0.4 cannot be installed

### ISSUE THREAD

**Issue by tangxj98** [Dao-AILab/flash-attention#1014]
I am trying to install scgpt which requires flash-attn. I am able to install flash-attn with the latest version but version 1.0.4 is required for scgpt to work with CUDA 11.7. When I tried to install the 1.0.4 version, I kept on get erros for :

Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]

      torch.__version__  = 1.13.1+cu117

      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8lyh9q8r/flash-attn_13ef38fe249a4240b0513366161d9049/setup.py", line 163, in <module>
          setup(
        File "~/scgpt/conda/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "~/scgpt/conda/setuptools/_distutils/core.py", line 171, in setup
          ok = dist.parse_command_line()
        File "~/scgpt/conda/setuptools/_distutils/dist.py", line 476, in parse_command_line
          args = self._parse_command_opts(parser, args)
        File "~/scgpt/conda/setuptools/dist.py", line 869, in _parse_command_opts
          nargs = _Distribution._parse_command_opts(self, parser, args)
        File "~/scgpt/conda/setuptools/_distutils/dist.py", line 535, in _parse_command_opts
          cmd_class = self.get_command_class(command)
        File "~/scgpt/conda/setuptools/dist.py", line 714, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "~/scgpt/conda/envs/scgpt/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "~/scgpt/conda/envs/scgpt/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'setuptools.command.bdist_wheel'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flash-attn)

I have setuptools 69.5.1 and wheel 0.43.0. 
Could someone help me with the problem?

**Comment by murphytju** [comment]
I meet the same question but can't solve it yet.

**Comment by underthesky77** [comment]
Hello, I also want to install scgpt and flash-attn 1.0.4 version, and encountered the same problem as you, did you solve it ?

**Comment by JaceWA99** [comment]
I am experiencing the same issue. A quick workaround is to app the pip flag `--no-build-isolation` when installing but there is a deeper issue that the build environment is never specified for pypi to construct the wheel (and so it can't find setuptools, torch, etc). Should be a simple pyproject.toml specification in the repo, though I'm not sure this version is still maintained.

**Comment by JaceWA99** [comment]
I tinkered with this more to get it to work for scgpt, conclusion is that it's better to just install flash attn with `--no-build-isolation` as a Docker command when building the image. If you really need it in pip without the flag I got a repo working that allows it to build within pip build env constraints. Be warned that this step alone can blow up docker size by 8-12 GB for the extra installs (torch), so again there's a reason they recommend the flag to drop the pip build env, saves the headache I had to go through. 
GitHub: https://github.com/JaceWA99/flash-attention-1.0.4-env
PyPi project: https://pypi.org/project/flash-attn-104-env/
