### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by alxmke** [Dao-AILab/flash-attention#1017]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools>pip install flash-attn
Collecting flash-attn
  Using cached flash_attn-2.5.9.post1.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from flash-attn) (2.1.0+cu121)
Requirement already satisfied: einops in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from flash-attn) (0.8.0)
Requirement already satisfied: filelock in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from torch->flash-attn) (3.13.1)
Requirement already satisfied: typing-extensions in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from torch->flash-attn) (4.9.0)
Requirement already satisfied: sympy in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from torch->flash-attn) (1.12)
Requirement already satisfied: networkx in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from torch->flash-attn) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from torch->flash-attn) (3.1.2)
Requirement already satisfied: fsspec in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from torch->flash-attn) (2023.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch->flash-attn) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\alex\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch->flash-attn) (1.3.0)
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [194 lines of output]
      fatal: not a git repository (or any of the parent directories): .git

      torch.__version__  = 2.1.0+cu121

      C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      Guessing wheel URL:  https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.9.post1/flash_attn-2.5.9.post1+cu122torch2.1cxx11abiFALSE-cp311-cp311-win_amd64.whl
      Precompiled wheel not found. Building from source...
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\flash_attn
      copying flash_attn\bert_padding.py -> build\lib.win32-cpython-311\flash_attn
      copying flash_attn\flash_attn_interface.py -> build\lib.win32-cpython-311\flash_attn
      copying flash_attn\flash_attn_triton.py -> build\lib.win32-cpython-311\flash_attn
      copying flash_attn\flash_attn_triton_og.py -> build\lib.win32-cpython-311\flash_attn
      copying flash_attn\flash_blocksparse_attention.py -> build\lib.win32-cpython-311\flash_attn
      copying flash_attn\flash_blocksparse_attn_interface.py -> build\lib.win32-cpython-311\flash_attn
      copying flash_attn\fused_softmax.py -> build\lib.win32-cpython-311\flash_attn
      copying flash_attn\__init__.py -> build\lib.win32-cpython-311\flash_attn
      creating build\lib.win32-cpython-311\flash_attn\layers
      copying flash_attn\layers\patch_embed.py -> build\lib.win32-cpython-311\flash_attn\layers
      copying flash_attn\layers\rotary.py -> build\lib.win32-cpython-311\flash_attn\layers
      copying flash_attn\layers\__init__.py -> build\lib.win32-cpython-311\flash_attn\layers
      creating build\lib.win32-cpython-311\flash_attn\losses
      copying flash_attn\losses\cross_entropy.py -> build\lib.win32-cpython-311\flash_attn\losses
      copying flash_attn\losses\__init__.py -> build\lib.win32-cpython-311\flash_attn\losses
      creating build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\baichuan.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\bert.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\bigcode.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\btlm.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\falcon.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\gpt.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\gptj.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\gpt_neox.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\llama.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\opt.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\vit.py -> build\lib.win32-cpython-311\flash_attn\models
      copying flash_attn\models\__init__.py -> build\lib.win32-cpython-311\flash_attn\models
      creating build\lib.win32-cpython-311\flash_attn\modules
      copying flash_attn\modules\block.py -> build\lib.win32-cpython-311\flash_attn\modules
      copying flash_attn\modules\embedding.py -> build\lib.win32-cpython-311\flash_attn\modules
      copying flash_attn\modules\mha.py -> build\lib.win32-cpython-311\flash_attn\modules
      copying flash_attn\modules\mlp.py -> build\lib.win32-cpython-311\flash_attn\modules
      copying flash_attn\modules\__init__.py -> build\lib.win32-cpython-311\flash_attn\modules
      creating build\lib.win32-cpython-311\flash_attn\ops
      copying flash_attn\ops\activations.py -> build\lib.win32-cpython-311\flash_attn\ops
      copying flash_attn\ops\fused_dense.py -> build\lib.win32-cpython-311\flash_attn\ops
      copying flash_attn\ops\layer_norm.py -> build\lib.win32-cpython-311\flash_attn\ops
      copying flash_attn\ops\rms_norm.py -> build\lib.win32-cpython-311\flash_attn\ops
      copying flash_attn\ops\__init__.py -> build\lib.win32-cpython-311\flash_attn\ops
      creating build\lib.win32-cpython-311\flash_attn\utils
      copying flash_attn\utils\benchmark.py -> build\lib.win32-cpython-311\flash_attn\utils
      copying flash_attn\utils\distributed.py -> build\lib.win32-cpython-311\flash_attn\utils
      copying flash_attn\utils\generation.py -> build\lib.win32-cpython-311\flash_attn\utils
      copying flash_attn\utils\pretrained.py -> build\lib.win32-cpython-311\flash_attn\utils
      copying flash_attn\utils\__init__.py -> build\lib.win32-cpython-311\flash_attn\utils
      creating build\lib.win32-cpython-311\flash_attn\ops\triton
      copying flash_attn\ops\triton\cross_entropy.py -> build\lib.win32-cpython-311\flash_attn\ops\triton
      copying flash_attn\ops\triton\k_activations.py -> build\lib.win32-cpython-311\flash_attn\ops\triton
      copying flash_attn\ops\triton\layer_norm.py -> build\lib.win32-cpython-311\flash_attn\ops\triton
      copying flash_attn\ops\triton\linear.py -> build\lib.win32-cpython-311\flash_attn\ops\triton
      copying flash_attn\ops\triton\mlp.py -> build\lib.win32-cpython-311\flash_attn\ops\triton
      copying flash_attn\ops\triton\rotary.py -> build\lib.win32-cpython-311\flash_attn\ops\triton
      copying flash_attn\ops\triton\__init__.py -> build\lib.win32-cpython-311\flash_attn\ops\triton
      running build_ext
      C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py:414: UserWarning: The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'flash_attn_2_cuda' extension
      creating C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311
      creating C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311\Release
      creating C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311\Release\csrc
      creating C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311\Release\csrc\flash_attn
      creating C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311\Release\csrc\flash_attn\src
      Emitting ninja build file C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311\Release\build.ninja...
      Compiling objects...
      Using envvar MAX_JOBS (3) as the number of workers...
      [1/49] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc -IC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\flash_attn -IC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\flash_attn\src -IC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\cutlass\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include\TH -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\flash_attn\flash_api.cpp /FoC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311\Release\csrc/flash_attn/flash_api.obj -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
      FAILED: C:/Users/Alex/AppData/Local/Temp/pip-install-dugioxdy/flash-attn_379fbc9640544033803e19127a0c0e3b/build/temp.win32-cpython-311/Release/csrc/flash_attn/flash_api.obj
      cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc -IC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\flash_attn -IC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\flash_attn\src -IC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\cutlass\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include\TH -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\include -IC:\Users\Alex\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\csrc\flash_attn\flash_api.cpp /FoC:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdninja: fatal: ReadFile: The handle is invalid.

      y\flash-attn_379fbc9640544033803e19127a0c0e3b\build\temp.win32-cpython-311\Release\csrc/flash_attn/flash_api.obj -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++17
      CreateProcess failed: The system cannot find the file specified.
      Traceback (most recent call last):
        File "C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\setup.py", line 271, in run
          urllib.request.urlretrieve(wheel_url, wheel_filename)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 241, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
                                  ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '3']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\setup.py", line 311, in <module>
          setup(
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Alex\AppData\Local\Temp\pip-install-dugioxdy\flash-attn_379fbc9640544033803e19127a0c0e3b\setup.py", line 288, in run
          super().run()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\build_ext.py", line 91, in run
          _build_ext.run(self)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 845, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flash-attn)

**Comment by gjd2017** [comment]
same errors....

**Comment by gohsyi** [comment]
Same error

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/tmp/pip-install-r07iqo56/flash-attn_739af491436844e9ac111fd5d64d99c0/setup.py", line 265, in run
    urllib.request.urlretrieve(wheel_url, wheel_filename)
  File "/miniconda/envs/openrlhf/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/miniconda/envs/openrlhf/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/miniconda/envs/openrlhf/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/miniconda/envs/openrlhf/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/miniconda/envs/openrlhf/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/miniconda/envs/openrlhf/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/miniconda/envs/openrlhf/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "/miniconda/envs/openrlhf/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "/tmp/pip-install-r07iqo56/flash-attn_739af491436844e9ac111fd5d64d99c0/setup.py", line 285, in <module>
    setup(
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/tmp/pip-install-r07iqo56/flash-attn_739af491436844e9ac111fd5d64d99c0/setup.py", line 282, in run
    super().run()
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 683, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/miniconda/envs/openrlhf/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
[end of output]

**Comment by kaishxu** [comment]
any ideas? same error!

**Comment by BeiYining** [comment]
same error.
`Command '['ninja', '-v', '-j', '12']' returned non-zero exit `

**Comment by JimWang151** [comment]
same error

**Comment by hananbeer** [comment]
same :(

**Comment by MathewCrespo** [comment]
same error

**Comment by WeizhenEricFang** [comment]
same error

**Comment by dr-ijaz** [comment]
same error

**Comment by lst627** [comment]
same error

**Comment by tjgrady** [comment]
Same issue

**Comment by xiaoc57** [comment]
A possible solution:
```bash
pip install flash-attn==2.3.6
```

**Comment by sina-sony** [comment]
In my case, I figured that there is no pre-built wheel for my PyTorch 2.6 for `flash-attn==2.3.6`.
So I just installed the latest version: `pip install flash-attn --no-build-isolation`.

**Comment by WelkinYang** [comment]
same

**Comment by wangh5738601** [comment]
I solved with pip install flash-attn==2.7.3    my enviroment cuda 11.8  torch 2.4.0

**Comment by aswordok** [comment]
> same error. `Command '['ninja', '-v', '-j', '12']' returned non-zero exit `

-v Correction --version , or -V.
Here the original author typed the wrong code.

**Comment by jxmorris12** [comment]
In my case I was using the `--no-cache-dir` argument. Got rid of this and it worked.

**Comment by martin-gou** [comment]
I solved it by using the **whl** file
1. download the corresponding version (cuda, torch) of whl file from github release. In my case, it's *flash_attn-2.7.1.post1+cu12torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl* from the [v2.7.1.post1](https://github.com/Dao-AILab/flash-attention/releases/tag/v2.7.1.post1)
2. then under my conda env, use the command 
```cmd 
pip install flash_attn-2.7.1.post1+cu12torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
```
3. then I use code below to check the validity
```python
import flash_attn
print(flash_attn.__version__)
```
4. and it worked! : )

**Comment by sfc-gh-sbekman** [comment]
if you want to skip cache lookup, which is what this error is about, set `FLASH_ATTENTION_FORCE_BUILD=TRUE`, e.g.:

```
FLASH_ATTENTION_FORCE_BUILD=TRUE pip install . --no-build-isolation --no-clean
```

this bypasses the online lookup.

**Comment by hlnull** [comment]
### Root Cause
The issue stems from version incompatibility among torch, python, and flash_attn.

### Solution
1. Add more descriptive messages in the relevant code section.
  In file xxx\Python311\Lib\urllib\request.py, line 643, modify:
  `raise HTTPError(req.full_url, code, msg, hdrs, fp)`
  to:
  `raise HTTPError(req.full_url, code, msg + ", req.full_url: '%s' " % (req.full_url), hdrs, fp)`

2. Get the error message.
The error occurred while reinstalling the flash-attn package using:
`pip install flash-attn --no-build-isolation`
The attempted download URL was:
`https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.9cxx11abiTRUE-cp311-cp311-linux_x86_64.whl`

3. Identify the version of flash_attn according to https://github.com/Dao-AILab/flash-attention/releases/

### Recommended Steps

1. Visit https://github.com/Dao-AILab/flash-attention/releases/ to browse available releases.
2. Identify a version of flash_attn compatible with your current torch and python versions.
3. Reinstall the appropriate packages accordingly.
