### ISSUE TITLE
Could not build wheels for flash-attn

### ISSUE THREAD

**Issue by FiReTiTi** [Dao-AILab/flash-attention#1026]
Hi,
I tried to install flash-attn Linux Centos 7.6.1810 and Python 3.9.19.

When I tried to install it, I got the following error:

    $  pip install flash-attn==2.5.8
    Collecting flash-attn==2.5.8
    ...
    Building wheels for collected packages: flash-attn
      Building wheel for flash-attn (setup.py) ... error
      error: subprocess-exited-with-error
  
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [20 lines of output]
          fatal: Not a git repository (or any parent up to mount point /tmp)
          Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
        
          torch.__version__  = 2.0.0
      
      
          /home/.../lib/python3.9/site-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
          !!
      
                  ********************************************************************************
                  Requirements should be satisfied by a PEP 517 installer.
                  If you are using pip, you can try `pip install --use-pep517`.
                  ********************************************************************************
      
          !!
            dist.fetch_build_eggs(dist.setup_requires)
          running bdist_wheel
          Guessing wheel URL:  https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu118torch2.0cxx11abiFALSE-cp39-cp39-linux_x86_64.whl
          error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1133)>
          [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for flash-attn
      Running setup.py clean for flash-attn
    Failed to build flash-attn
    ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects

When I try to add "--use-pep517" as suggested, then I get the following error:

    $  pip install --use-pep517 flash-attn==2.5.8
    Collecting flash-attn==2.5.8
      Using cached flash_attn-2.5.8.tar.gz (2.5 MB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... error
      error: subprocess-exited-with-error

      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Traceback (most recent call last):  
            File "/home/.../lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/.../lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/.../lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
              return hook(config_settings)
            File "/tmp/pip-build-env-omdlofs_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
              return self._get_build_requires(config_settings, requirements=[])
            File "/tmp/pip-build-env-omdlofs_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
              self.run_setup()
            File "/tmp/pip-build-env-omdlofs_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
              super().run_setup(setup_script=setup_script)
            File "/tmp/pip-build-env-omdlofs_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
              exec(code, locals())
            File "<string>", line 9, in <module>
          ModuleNotFoundError: No module named 'packaging'
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.

The most up to date version of "packaging" already exists.
I read that "setuptools" might the source of the issue, so I tried using 69.5.1 and 70.0.2, same problems

Please advise

**Comment by FiReTiTi** [comment]
I downloaded the file directly from the archive and I was able to install it.

**Comment by Sayli2000** [comment]
> I downloaded the file directly from the archive and I was able to install it.

How do you do that?

**Comment by FiReTiTi** [comment]
@aurianer Thanks, I'll give it a try.

**Comment by JacobFV** [comment]
That sounds like such a GH comment

**Comment by rzgarespo** [comment]
pre-built Wheels: https://github.com/Dao-AILab/flash-attention/releases
_Often, pip automatically prefers to download these wheels if they are available. However, when it falls back to building from source, it could be due to a version incompatibility or if there is not a pre-built wheel for your system._
