### ISSUE TITLE
illegal memory access was encountered when processing 20000 tokens with return_softmax

### ISSUE THREAD

**Issue by YJHMITWEB** [Dao-AILab/flash-attention#1054]
I tried both `pip install flash-attn` as well as `building from source`, both give the following error:
```
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Typically, if the sequence length is too long, and `return_softmax` is set to `True`, it raises the error.

My system:
```
CUDA: 11.8
Torch: 2.3.1
GPU: A100 80G
```

To reproduce:
```
import torch
from flash_attn.flash_attn_interface import _flash_attn_forward, _flash_attn_backward

q = torch.randn((1, 50000, 1, 128), dtype=torch.half, device='cuda:0')
k = torch.randn((1, 50000, 1, 128), dtype=torch.half, device='cuda:0')
v = torch.randn((1, 50000, 1, 128), dtype=torch.half, device='cuda:0')

block_out, _, _, _, _, block_lse, _, _ = _flash_attn_forward(
                                                            q,
                                                            k,
                                                            v,
                                                            0.1,
                                                            128 ** (-0.5),
                                                            causal=True,
                                                            window_size=(-1, -1),
                                                            alibi_slopes=None,
                                                            softcap=0.0,
                                                            return_softmax=True
                                                        )

torch.cuda.synchronize()
```

I also tried the following tensor shape which also errors:
```
(1, 20000, 8, 128),
(1, 25000, 5, 128),
(1, 32768, 6, 128),
...
```
I saw similar issues being posted before at #338.

**Comment by tridao** [comment]
I ran the script and there's no error. Are there other ways to reproduce the error?

**Comment by YJHMITWEB** [comment]
@tridao Hi, I tried another environment which also gives the same error:

```
CUDA: 12.1
Torch: 2.2.0
GPU: A100 40G
```

The full log is:
```
python test_fa.py 
Traceback (most recent call last):
  File "/test_ops/test_fa.py", line 20, in <module>
    torch.cuda.synchronize()
  File "/miniconda3/envs/ai_general/lib/python3.10/site-packages/torch/cuda/__init__.py", line 801, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

The error comes at `torch.cuda.synchronize()`, if I comment out the sync, no errors will show.

**Comment by YJHMITWEB** [comment]
I did some rough pinpoint on the potential issue, if I comment out the `if` branch on [return_softmax](https://github.com/Dao-AILab/flash-attention/blob/7ef24848cf2f855077cef88fe122775b727dcd74/csrc/flash_attn/src/flash_fwd_kernel.h#L355) and [return_softmax](https://github.com/Dao-AILab/flash-attention/blob/7ef24848cf2f855077cef88fe122775b727dcd74/csrc/flash_attn/src/flash_fwd_kernel.h#L355), the issue will gone.

`flash-attention/tree/main/csrc/flash_attn/src/flash_fwd_kernel.h`, Line 355
```
if (Return_softmax) {
    Tensor rP_drop = make_fragment_like(rP);
    cute::copy(rP, rP_drop);
    dropout.template apply_dropout</*encode_dropout_in_sign_bit=*/true>(
        rP_drop, block_row_idx, block_col_idx, kNWarps
    );
    cute::copy(rP_drop, tSgS);
    tSgS.data() = tSgS.data() + (-kBlockN);
}
```

`flash-attention/tree/main/csrc/flash_attn/src/flash_fwd_kernel.h`, Line 417
```
if (Return_softmax) {
    Tensor rP_drop = make_fragment_like(rP);
    cute::copy(rP, rP_drop);
    dropout.template apply_dropout</*encode_dropout_in_sign_bit=*/true>(
        rP_drop, block_row_idx, block_col_idx, kNWarps
    );
    cute::copy(rP_drop, tSgS);
    tSgS.data() = tSgS.data() + (-kBlockN);
}
```

**Comment by tridao** [comment]
I'm confused, `Return_softmax` is False unless there's dropout. Are you sure you're not using dropout?

**Comment by YJHMITWEB** [comment]
I use `dropout`, it is set to `0.1` in the above script.

**Comment by tridao** [comment]
What's probably happening is that the softmax matrix is very large (20k x 20k), depending on batch size etc can have size more than 2GB. We use 32 bit indexing (to save registers) so for arrays larger than 2GB the indexing might be wrong, causing IMA.
As mentioned in the doc string, "return_softmax" is only meant to be used for testing.

**Comment by YJHMITWEB** [comment]
Oh I see, understand. Thanks, @tridao
