### ISSUE TITLE
FA3 setup install issue, mainloop_fwd_sm90_tma_gmma_ws issue.

### ISSUE THREAD

**Issue by praveenperfecto** [Dao-AILab/flash-attention#1091]
FAILED: /data/data/testing_version_flash/flash-attention/hopper/build/temp.linux-x86_64-cpython-310/flash_fwd_hdim128_fp8_sm90.o 
/usr/local/cuda-12.3/bin/nvcc --generate-dependencies-with-compile --dependency-output /data/data/testing_version_flash/flash-attention/hopper/build/temp.linux-x86_64-cpython-310/flash_fwd_hdim128_fp8_sm90.o.d -I/data/data/testing_version_flash/flash-attention/csrc/cutlass/include -I/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/include -I/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/include/TH -I/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-12.3/include -I/root/miniconda3/envs/newflashenv/include/python3.10 -c -c /data/data/testing_version_flash/flash-attention/hopper/flash_fwd_hdim128_fp8_sm90.cu -o /data/data/testing_version_flash/flash-attention/hopper/build/temp.linux-x86_64-cpython-310/flash_fwd_hdim128_fp8_sm90.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=--verbose,--register-usage-level=10,--warn-on-local-memory-usage -lineinfo -DCUTLASS_DEBUG_TRACE_LEVEL=0 -DNDEBUG -DQBLKSIZE=128 -DKBLKSIZE=128 -DCTA256 -DDQINRMEM -DEXECMODE=0 -gencode arch=compute_90a,code=sm_90a --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=flashattn_hopper_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -ccbin gcc
/data/data/testing_version_flash/flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp(112): error: identifier "StrideQKV" is undefined
          make_tensor(make_gmem_ptr(static_cast<Element const*>(nullptr)), repeat_like(StrideQKV{}, int32_t(0)), StrideQKV{}),
                                                                                       ^

/data/data/testing_version_flash/flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp(112): error: expected a ")"
          make_tensor(make_gmem_ptr(static_cast<Element const*>(nullptr)), repeat_like(StrideQKV{}, int32_t(0)), StrideQKV{}),
                                                                                                ^

/data/data/testing_version_flash/flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp(112): error: no instance of function template "cute::repeat_like" matches the argument list
            argument types are: (<error-type>)
          make_tensor(make_gmem_ptr(static_cast<Element const*>(nullptr)), repeat_like(StrideQKV{}, int32_t(0)), StrideQKV{}),
                                                                           ^

/data/data/testing_version_flash/flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp(112): error: expected a ")"
          make_tensor(make_gmem_ptr(static_cast<Element const*>(nullptr)), repeat_like(StrideQKV{}, int32_t(0)), StrideQKV{}),
                                                                                                                          ^

/data/data/testing_version_flash/flash-attention/hopper/mainloop_fwd_sm90_tma_gmma_ws.hpp(115): error: expected a ";"
          size<0>(ClusterShape{})));
                                  ^

/data/data/testing_version_flash/flash-attention/hopper/flash_fwd_launch_template.h(98): warning #549-D: variable "status_" is used before its value is set
        do { cudaError_t status_ = status_; if (status_ != cudaSuccess) { fprintf(
                                   ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

5 errors detected in the compilation of "/data/data/testing_version_flash/flash-attention/hopper/flash_fwd_hdim128_fp8_sm90.cu".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/testing_version_flash/flash-attention/hopper/setup.py", line 260, in <module>
    setup(
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/command/install.py", line 87, in run
    self.do_egg_install()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/command/install.py", line 139, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 683, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/root/miniconda3/envs/newflashenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by tridao** [comment]
I messed up the most recent merge, will fix today.

**Comment by qibaoyuan** [comment]
> I messed up the most recent merge, will fix today.

sorry to bother, any update now?
