### ISSUE TITLE
Install flash-attn 2 with cuda 12 : flash-attn is looking for cuda 11

### ISSUE THREAD

**Issue by YerongLi** [Dao-AILab/flash-attention#1122]
I have cuda 12 while I find flash-attn is still looking for cuda 11
```
>>> from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yerong2/local/miniconda3/envs/intern/lib/python3.9/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/yerong2/local/miniconda3/envs/intern/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

**Comment by jpli02** [comment]
same isuue

**Comment by DrChiZhang** [comment]
> I have cuda 12 while I find flash-attn is still looking for cuda 11
> 
> ```
> >>> from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/yerong2/local/miniconda3/envs/intern/lib/python3.9/site-packages/flash_attn/__init__.py", line 3, in <module>
>     from flash_attn.flash_attn_interface import (
>   File "/home/yerong2/local/miniconda3/envs/intern/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
>     import flash_attn_2_cuda as flash_attn_cuda
> ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
> ```

did you find any solution?

**Comment by 2013303386** [comment]
same problem

**Comment by eoastafurov** [comment]
same for me

**Comment by jpli02** [comment]
try this command
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH

**Comment by wangyuyy** [comment]
@jpli02 Thanks a lot, this works for me. But may I sincerely ask why this operation works?

**Comment by LukeLIN-web** [comment]
> [@jpli02](https://github.com/jpli02) Thanks a lot, this works for me. But may I sincerely ask why this operation works?

I think cuda is install in conda But flashattention cannot find it
