### ISSUE TITLE
install flash-attn error windows 11

### ISSUE THREAD

**Issue by AbsoluteMode** [Dao-AILab/flash-attention#1193]
hello, can u help me pls <3
windows 11
3090ti
RAM 64gb ddr5
cuda 12.1
torch2.4

Location Russia

pip install flash-attn --no-build-isolation
Building wheel for flash-attn (setup.py) ... \

...
  ЏаЁ¬Ґз ­ЁҐ: ўЄ«озҐ­ЁҐ д ©« :     C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\torch\include\ATen/Generator.h
      ЏаЁ¬Ґз ­ЁҐ: ўЄ«озҐ­ЁҐ д ©« :  C:\Users\lesny\AppData\Local\Temp\pip-install-o9ph9y9s\flash-attn_de2a56c006c943dd96af09d516685972\csrc\flash_attn\src\static_switch.h
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\lesny\AppData\Local\Temp\pip-install-o9ph9y9s\flash-attn_de2a56c006c943dd96af09d516685972\setup.py", line 450, in run
          urllib.request.urlretrieve(wheel_url, wheel_filename)
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
          with contextlib.closing(urlopen(url, data)) as fp:
                                  ^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
          response = meth(req, response)
                     ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
          response = self.parent.error(
                     ^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
          return self._call_chain(*args)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\torch\utils\cpp_extension.py", line 2105, in _run_ninja_build
          subprocess.run(
        File "C:\Users\lesny\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '2']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lesny\AppData\Local\Temp\pip-install-o9ph9y9s\flash-attn_de2a56c006c943dd96af09d516685972\setup.py", line 490, in <module>
          setup(
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\dist.py", line 953, in run_commands
          self.run_command(cmd)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\dist.py", line 972, in run_command
          cmd_obj.run()
        File "C:\Users\lesny\AppData\Local\Temp\pip-install-o9ph9y9s\flash-attn_de2a56c006c943dd96af09d516685972\setup.py", line 467, in run
          super().run()
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\wheel\_bdist_wheel.py", line 378, in run
          self.run_command("build")
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\dist.py", line 972, in run_command
          cmd_obj.run()
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\dist.py", line 972, in run_command
          cmd_obj.run()
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\command\build_ext.py", line 98, in run
          _build_ext.run(self)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\torch\utils\cpp_extension.py", line 866, in build_extensions
          build_ext.build_extensions(self)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\command\build_ext.py", line 263, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\torch\utils\cpp_extension.py", line 838, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\torch\utils\cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\Users\lesny\vikhr\cuda12.1\Lib\site-packages\torch\utils\cpp_extension.py", line 2121, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flash-attn)

**Comment by whois206** [comment]
我也一样苦，花了二天了。也没解决！
nvcc --version
 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:26:51_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0

flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.    
The installation is prompted to be successful, but it still cannot be used

**Comment by NoguchiRyo** [comment]
Hi. I got the same error when I tried to build the package with Windows11 and gave up.
Instead, I found the pre-build wheel for Windows11 in this repository.
https://github.com/oobabooga/flash-attention
I downloaded the latest wheel file from the release page and installed it with pip.
I briefly tested flash_attn_func function with small tensors, and got no error, so I guess it worked.
(I use torch 2.4.1+cu124 and CUDA12.4, python3.11
 And I installed this https://github.com/oobabooga/flash-attention/releases/download/v2.6.3/flash_attn-2.6.3+cu122torch2.4.0cxx11abiFALSE-cp311-cp311-win_amd64.whl)
I hope this helps you.

**Comment by whois206** [comment]
正在尝试，我英文差，勉强能看懂，表达不了！

**Comment by whois206** [comment]
很高兴得到你的帮助，成功的安装了！谢谢~~
________________________________
发件人: Ryo Noguchi ***@***.***>
发送时间: 2024年9月16日 17:25
收件人: Dao-AILab/flash-attention ***@***.***>
抄送: whois206 ***@***.***>; Comment ***@***.***>
主题: Re: [Dao-AILab/flash-attention] install flash-attn error windows 11 (Issue #1193)


Hi. I got the same error when I tried to build the package with Windows11 and gave up.
Instead, I found the pre-build wheel for Windows11 in this repository.
https://github.com/oobabooga/flash-attention
I downloaded the latest wheel file from the release page and installed it with pip.
I briefly tested flash_attn_func function with small tensors, and got no error, so I guess it worked.
(I use torch 2.4.1+cu124 and CUDA12.4, python3.11
And I installed this https://github.com/oobabooga/flash-attention/releases/download/v2.6.3/flash_attn-2.6.3+cu122torch2.4.0cxx11abiFALSE-cp311-cp311-win_amd64.whl)
I hope this helps you.

―
