### ISSUE TITLE
Pytorch 2.4.1 with flash-attn 2.5.8

### ISSUE THREAD

**Issue by adtian2** [Dao-AILab/flash-attention#1226]
For my specific use-case, I need to get flash-attn 2.5.8 working with Pytorch 2.4.1. There is no existing wheel in the release list of flash-attn 2.5.8 that is compiled with Pytorch 2.4. I tried to build from source using these commands below:
```python
git clone https://github.com/Dao-AILab/flash-attention.git
MAX_JOBS=16 CUDA_HOME="/opt/conda" python setup.py build
MAX_JOBS=16 CUDA_HOME="/opt/conda" python setup.py install
```

But I am finding that it gives me this error:
```
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '16']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/flash-attention/setup.py", line 311, in <module>
    setup(
  File "/opt/conda/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/opt/conda/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

Is there a way to get this build process to work? Or is there a way for me to build my own wheel in my environment?

**Comment by tridao** [comment]
Try reducing MAX_JOBS

**Comment by adtian2** [comment]
Thanks, that worked! Resolving
