### ISSUE TITLE
No module named moe_kernel in Flash Attention Installation

### ISSUE THREAD

**Issue by abhasin14** [Dao-AILab/flash-attention#1262]
**Task - Flash Attention Installation from Source. [Completed]
Run- TGI2.3.1 with models that support for Flash attention enabled models.** 

**Error -** 
2024-10-08T09:26:27.562016Z  INFO text_generation_launcher: Using prefix caching = True
2024-10-08T09:26:27.562042Z  INFO text_generation_launcher: Using Attention = flashinfer
2024-10-08T09:26:28.345909Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'moe_kernels'
2024-10-08T09:26:28.555288Z  WARN text_generation_launcher: Could not import Mamba: No module named 'causal_conv1d'
2024-10-08T09:26:29.238808Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "tgi_new_env/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "tgi_new_env/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "tgi_new_env/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "tgi_new_env/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "tgi_new_env/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "tgi_new_env/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/remote/vg_llm/anmolb/tgi/tgi_new_env/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "tgi_new_env/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "tgi_new_env/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "text-generation-inference-2.3.1/server/text_generation_server/cli.py", line 109, in serve
    server.serve(
  File "/text-generation-inference-2.3.1/server/text_generation_server/server.py", line 280, in serve
    asyncio.run(
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "text-generation-inference-2.3.1/server/text_generation_server/server.py", line 235, in serve_inner
    model = get_model_with_lora_adapters(
  File "text-generation-inference-2.3.1/server/text_generation_server/models/__init__.py", line 1277, in get_model_with_lora_adapters
    model = get_model(
  File "text-generation-inference-2.3.1/server/text_generation_server/models/__init__.py", line 843, in get_model
    raise NotImplementedError(FLASH_ATT_ERROR_MESSAGE.format("Sharded Llama"))
NotImplementedError: Sharded Llama requires Flash Attention enabled models.

The result of pip show flash-attn to show Flash Attention:

Name: flash_attn
Version: 2.6.3
Summary: Flash Attention: Fast and Memory-Efficient Exact Attention
Home-page: https://github.com/Dao-AILab/flash-attention
Author: Tri Dao
Author-email: tri@tridao.me
License: 
Location: tgi_new_env/lib/python3.9/site-packages/flash_attn-2.6.3-py3.9-linux-x86_64.egg
Requires: einops, torch
Required-by:

**Comment by tridao** [comment]
This issue is better asked on the TGI github.
