### ISSUE TITLE
Unable to import my new kernel function after compilation success.

### ISSUE THREAD

**Issue by jpli02** [Dao-AILab/flash-attention#1278]
Hi,
I am build a new flash_attn kernle function and trying to compile and import.
Before adding new kernle function and new .cu file, I can successfully build from source and use it.

I have added a new .cu file called flash_fwd_hdim32_fp16_sm80_accum.cu:
**flash_fwd_hdim32_fp16_sm80_accum.cu code:**
#include "flash_fwd_launch_template.h"

template<>
void run_mha_fwd_accum_<cutlass::half_t, 32>(Flash_fwd_params &params, cudaStream_t stream) {
    run_mha_fwd_hdim32_accum<cutlass::half_t>(params, stream);
}

**I also add this file into setup.py**
<img width="723" alt="Screenshot 2024-10-15 at 12 54 08 PM" src="https://github.com/user-attachments/assets/77cf792d-eb90-48f5-936e-c6fcfafde859">

I am using torch 2.1.0+cu118 on A40 GPU.

I am building from source : pip install . --no-build-isolation -v
**The compilation is successful but when I try to import flash_attn, there is an error.**

Successfully installed flash_attn-2.5.8 
(ok) $ python
Python 3.9.19 (main, May  6 2024, 19:43:03) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/flash-attention/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/u/flash-attention/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /scratch/bcjw/anaconda3/envs/ok/lib/python3.9/site-packages/flash_attn_2_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z18run_mha_fwd_accum_IN7cutlass6half_tELi224EEvR16Flash_fwd_paramsP11CUstream_st

Is there anything I need to modify so that I can make the import works?

**Comment by tridao** [comment]
You'd probably want to add a declaration in `flash.h` (see the last 3 lines of `flash.h`).

**Comment by jpli02** [comment]
Thanks for your reply!
I have already added one before in flash.h:

<img width="1167" alt="Screenshot 2024-10-15 at 1 05 33 PM" src="https://github.com/user-attachments/assets/ffc98208-9ca7-4ec2-8d93-c65605741094">
