### ISSUE TITLE
ROCm compilation error with PyTorch 2.5.1

### ISSUE THREAD

**Issue by calebthomas259** [Dao-AILab/flash-attention#1307]
Hello,

I get an error when trying to compile flash attention for ROCm using PyTorch 2.5.1 (but for some reason, PyTorch 2.4.1 works okay).

I'm using an AMD MI250X GPU.

Here's a minimal example (it assumes that miniconda is already installed):
1. Create a new Python environment: `conda create -n test_251 python=3.11 && conda activate test_251`
2. Install PyTorch 2.5.1: `pip install -v torch==2.5.1+rocm6.2 --index-url https://download.pytorch.org/whl/rocm6.2`
3. Install packaging: `pip install packaging`
4. Download flash attention and checkout the latest main commit (at time of writing): `git clone https://github.com/Dao-AILab/flash-attention.git && cd flash-attention && git checkout 478ee666cccbd1b8f63648633003059a8dc6827d`
5. Try compiling: `BUILD_TARGET=rocm python setup.py install`

Here's a relevant output snippet, showing the error message:

```sh
...
[23/2334] /opt/rocm-5.7.1/bin/hipcc  -I/tmp/conda/flash-attention/csrc/composable_kernel/include -I/tmp/conda/flash-attention/csrc/composable_kernel/library/include -I/tmp/conda/flash-attention/csrc/composable_kernel/example/ck_tile/01_fmha -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/TH -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/THC -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/THH -I/opt/rocm-5.7.1/include -I/tmp/conda/opt/conda/envs/test_251/include/python3.11 -c -c /tmp/conda/flash-attention/build/fmha_bwd_convert_dq_d128_fp16_b64x128_group_o2_ps.hip -o /tmp/conda/flash-attention/build/temp.linux-x86_64-cpython-311/build/fmha_bwd_convert_dq_d128_fp16_b64x128_group_o2_ps.o -fPIC -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DHIPBLAS_V2 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 --offload-arch=native -O3 -std=c++17 -DCK_TILE_FMHA_FWD_FAST_EXP2=1 -fgpu-flush-denormals-to-zero -DCK_ENABLE_BF16 -DCK_ENABLE_BF8 -DCK_ENABLE_FP16 -DCK_ENABLE_FP32 -DCK_ENABLE_FP64 -DCK_ENABLE_FP8 -DCK_ENABLE_INT8 -DCK_USE_XDL -DUSE_PROF_API=1 -D__HIP_PLATFORM_HCC__=1 -DCK_TILE_FLOAT_TO_BFLOAT16_DEFAULT=3 -fno-offload-uniform-block -mllvm -enable-post-misched=0 -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -mllvm -amdgpu-coerce-illegal-types=1 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -fno-gpu-rdc
FAILED: /tmp/conda/flash-attention/build/temp.linux-x86_64-cpython-311/build/fmha_bwd_convert_dq_d128_fp16_b64x128_group_o2_ps.o
/opt/rocm-5.7.1/bin/hipcc  -I/tmp/conda/flash-attention/csrc/composable_kernel/include -I/tmp/conda/flash-attention/csrc/composable_kernel/library/include -I/tmp/conda/flash-attention/csrc/composable_kernel/example/ck_tile/01_fmha -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/TH -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/THC -I/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/include/THH -I/opt/rocm-5.7.1/include -I/tmp/conda/opt/conda/envs/test_251/include/python3.11 -c -c /tmp/conda/flash-attention/build/fmha_bwd_convert_dq_d128_fp16_b64x128_group_o2_ps.hip -o /tmp/conda/flash-attention/build/temp.linux-x86_64-cpython-311/build/fmha_bwd_convert_dq_d128_fp16_b64x128_group_o2_ps.o -fPIC -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DHIPBLAS_V2 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 --offload-arch=native -O3 -std=c++17 -DCK_TILE_FMHA_FWD_FAST_EXP2=1 -fgpu-flush-denormals-to-zero -DCK_ENABLE_BF16 -DCK_ENABLE_BF8 -DCK_ENABLE_FP16 -DCK_ENABLE_FP32 -DCK_ENABLE_FP64 -DCK_ENABLE_FP8 -DCK_ENABLE_INT8 -DCK_USE_XDL -DUSE_PROF_API=1 -D__HIP_PLATFORM_HCC__=1 -DCK_TILE_FLOAT_TO_BFLOAT16_DEFAULT=3 -fno-offload-uniform-block -mllvm -enable-post-misched=0 -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -mllvm -amdgpu-coerce-illegal-types=1 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -fno-gpu-rdc
clang (LLVM option parsing): Unknown command line argument '-amdgpu-coerce-illegal-types=1'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--amdgpu-mode-register=1'?
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '23']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/conda/flash-attention/setup.py", line 508, in <module>
    setup(
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/command/install.py", line 97, in run
    self.do_egg_install()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/command/install.py", line 149, in do_egg_install
    self.run_command('bdist_egg')
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 168, in run
    cmd = self.call_command('install_lib', warn_dir=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/command/bdist_egg.py", line 154, in call_command
    self.run_command(cmdname)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 868, in build_extensions
    build_ext.build_extensions(self)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 681, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1784, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/tmp/conda/opt/conda/envs/test_251/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2120, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

If I change step 2 to use PyTorch 2.4.1 instead (`pip install -v torch==2.4.1+rocm6.1 --index-url https://download.pytorch.org/whl/rocm6.1`) then everything works. Unfortunately, I need PyTorch 2.5 to fix a different bug, otherwise I could keep using PyTorch 2.4...

I can't find any related code in the PyTorch repo, so as far as I can tell, the issue is caused by the ROCm 6.1 -> 6.2 change together with the command line flag `-amdgpu-coerce-illegal-types`. There's also [this commit](https://github.com/ROCm/composable_kernel/commit/ae3b8ff86c7796c0146d2b014903ed7b7483ca4a) from the composable-kernel repo which may be relevant.

Thank you for the help!

@rocking5566

**Comment by rocking5566** [comment]
1. Could you share your hip version? by `hipcc --version`
2. I found your error show 
`clang (LLVM option parsing): Unknown command line argument '-amdgpu-coerce-illegal-types=1'`
Could you try to remove these two lines?
https://github.com/Dao-AILab/flash-attention/blob/main/setup.py#L387-L388

**Comment by jiagaoxiang** [comment]
> 1. Could you share your hip version by `hipcc --version`
> 2. I found your error show
>    `clang (LLVM option parsing): Unknown command line argument '-amdgpu-coerce-illegal-types=1'`
>    Could you try to remove these two lines?
>    https://github.com/Dao-AILab/flash-attention/blob/main/setup.py#L387-L388

It fixed my error.

**Comment by calebthomas259** [comment]
> 1. Could you share your hip version by `hipcc --version`

Here's the output from `hipcc --version`:
```
HIP version: 5.7.31921-1949b1621
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.7.1 23382 f3e174a1d286158c06e4cc8276366b1d4bc0c914)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.7.1/llvm/bin
```

I think I may have been using ROCm toolkit 5.7 (pre-installed by the computing cluster) all this time without realising it. When I run `type hipcc` while the conda environment is active, it points to `usr/bin/hipcc`, whereas I was expecting the path to be somewhere in the conda installation directory.

Does `pip install torch` download the full ROCm toolkit as well as the ROCM runtime? If not, is there a standalone conda/pip package that has the full ROCM toolkit, or do I need to use the Docker image?

> 2. I found your error show
>    `clang (LLVM option parsing): Unknown command line argument '-amdgpu-coerce-illegal-types=1'`
>    Could you try to remove these two lines?
>    https://github.com/Dao-AILab/flash-attention/blob/main/setup.py#L387-L388

I didn't realise that `-amdgpu-coerce-illegal-types` was used directly in the setup.py file. Removing these two lines fixes the error! But it's probably better if I fix my ROCm installation.

Thank you for the prompt help, I really appreciate it.

**Comment by rocking5566** [comment]
Hi @calebthomas259 
Does pip install torch download the full ROCm toolkit as well as the ROCM runtime?
>> Sorry, I don't know about what pip install torch actually doing... and... I am the docker user
I develop flash attention base on rocm pytorch docker image 
https://hub.docker.com/r/rocm/pytorch/tags
