### ISSUE TITLE
Package is uninstallable

### ISSUE THREAD

**Issue by chrisspen** [Dao-AILab/flash-attention#1313]
The package complains about "torch" not being installed when it is most definitely installed.

    (.env) chris@localhost:~$ pip install flash_attn
    Collecting flash_attn
      Using cached flash_attn-2.6.3.tar.gz (2.6 MB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... error
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [20 lines of output]
          Traceback (most recent call last):
            File "/home/chris/git/llm-test/qwen/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
              main()
            File "/home/chris/git/llm-test/qwen/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/chris/git/llm-test/qwen/.env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
              return hook(config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-3joybpdk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
              return self._get_build_requires(config_settings, requirements=[])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/tmp/pip-build-env-3joybpdk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
              self.run_setup()
            File "/tmp/pip-build-env-3joybpdk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 521, in run_setup
              super().run_setup(setup_script=setup_script)
            File "/tmp/pip-build-env-3joybpdk/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 319, in run_setup
              exec(code, locals())
            File "<string>", line 21, in <module>
          ModuleNotFoundError: No module named 'torch'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    (.env) chris@localhost:~$ pip freeze|grep -i torch
    torch==2.5.1
    torchvision==0.20.1

Running Ubuntu 24.04.

**Comment by LaaZa** [comment]
I think you need `--no-build-isolation`, but the build will likely take forever, so if you can, wait for torch 2.5.1 wheels or downgrade torch to 2.4.
