### ISSUE TITLE
FP8 test failure on the latest 'decode' branch

### ISSUE THREAD

**Issue by cscyuge** [Dao-AILab/flash-attention#1352]
**Describe the bug**
While testing the 'decode' branch of the FlashAttention project, I encountered a failure in the FP8 tests.

**To Reproduce**
in the test_flash_attn.py, run tests:
```
test_flash_attn_output(
        seqlen_q=4,
        seqlen_k=4096,
        d=128,
        causal=True,
        local=False,
        softcap=0.0,
        V_colmajor=False,
        deterministic=True,
        mha_type="gqa",
        dtype=torch.float8_e4m3fn
    )
```
```
test_flash_attn_varlen_output(
        seqlen_q=4,
        seqlen_k=4096,
        d=128,
        causal=True,
        local=False,
        softcap=0.0,
        deterministic=True,
        mha_type="gqa",
        dtype=torch.float8_e4m3fn
    )
```
    
output messages:
```
Output max diff: 0.83203125
Output mean diff: 0.09228515625
Pytorch max diff: 0.0771484375
Pytorch mean diff: 0.0145263671875
Traceback (most recent call last):
  File "/workspace/flash-attention/hopper/test_flash_attn.py", line 1144, in <module>
    test_flash_attn_output(
  File "/workspace/flash-attention/hopper/test_flash_attn.py", line 479, in test_flash_attn_output
    assert (out - out_ref).abs().max().item() <= multiple * (out_pt - out_ref).abs().max().item()
AssertionError
```
```
Output max diff: 4.5
Output mean diff: 0.51171875
Pytorch max diff: 0.042724609375
Pytorch mean diff: 0.00537109375
Traceback (most recent call last):
  File "/workspace/flash-attention/hopper/test_flash_attn.py", line 1156, in <module>
    test_flash_attn_varlen_output(
  File "/workspace/flash-attention/hopper/test_flash_attn.py", line 689, in test_flash_attn_varlen_output
    assert (out - out_ref).abs().max().item() <= 2 * (out_pt - out_ref).abs().max().item()
AssertionError
```

I was testing in a container using the NVIDIA PyTorch image nvcr.io/nvidia/pytorch:24.05-py3.

I was wondering if there is an estimated timeline for fixing this issue or if there are any workarounds or temporary solutions available? I appreciate your help and any guidance you can provide.

Looking forward to hearing from you. Thank you!

**Comment by tridao** [comment]
The FP8 templates are currently commented out. We'll get to FP8 decoding soon
https://github.com/Dao-AILab/flash-attention/blob/bc8a001d8da4112add2f72534016ef1cc810c43f/hopper/flash_fwd_launch_template.h#L214
