### ISSUE TITLE
ImportError: cannot import name 'flash_attn_qkvpacked_func' from 'flash_attn'

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Dao-AILab/flash-attention#318]
Hey :wave: Like title, after installing it using docker 

```yaml
FROM nvcr.io/nvidia/pytorch:23.06-py3

RUN pip install -U ninja packaging
RUN pip install flash-attn --no-build-isolation

CMD [ "/bin/bash" ]
```

and running 

```
docker run --rm -it --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
 -v $PWD:/workspace  flash-attention-2 
```

then running python and inside it 

```
>>> from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
```

resulted in 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'flash_attn_qkvpacked_func' from 'flash_attn' (/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py)
```

Thanks

**Comment by FrancescoSaverioZuppichini** [comment]
version is one 

```
>>> import flash_attn
>>> flash_attn.__version__
'1.0.7'
```

**Comment by tridao** [comment]
PyPI lists version 2.0.0.post1 so idk why it would install version 1.

**Comment by tridao** [comment]
You might need to rebuild docker so that `pip install flash-attn --no-build-isolation` get triggered?

**Comment by FrancescoSaverioZuppichini** [comment]
It crashed my pc again :(

**Comment by ShomyLiu** [comment]
If using ngc-pytorch, I try to pip uninstall transformer-engine,  it will work.

**Comment by SaiPrahladh** [comment]
Did this issue get resolved? I am running into a similar ImportError
```python
>>> import torch
>>> torch.__version__
'2.0.1+cu118'
>>> import flash_attn
>>> flash_attn.__version__
'2.3.2'
>>> from flash_attn.flash_attn_interface import flash_attn_unpadded_qkvpacked_func
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'flash_attn_unpadded_qkvpacked_func' from 'flash_attn.flash_attn_interface' (/home/sai.prahladh/.local/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py)

``` 
I installed flash_attn using the command:
```shell
pip install flash-attn --no-build-isolation
```

**Comment by tridao** [comment]
As mentioned in the README
```
Upgrading from FlashAttention (1.x) to FlashAttention-2

These functions have been renamed:

flash_attn_unpadded_func -> flash_attn_varlen_func
flash_attn_unpadded_qkvpacked_func -> flash_attn_varlen_qkvpacked_func
flash_attn_unpadded_kvpacked_func -> flash_attn_varlen_kvpacked_func
```

**Comment by SaiPrahladh** [comment]
Thanks for the prompt reply @tridao. My bad that I didn't check the changelog properly!

**Comment by maidouwang123** [comment]
I got a problem here, and I already installed flash-attn 0.2.8 and ninja 1.11.1.4 :                                                                                                                                                    
 /data/MST/MST-main/mst/models/extern/dinov2/layers/swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
/data/MST/MST-main/mst/models/extern/dinov2/layers/attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
/data/MST/MST-main/mst/models/extern/dinov2/layers/block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")
Traceback (most recent call last):
  File "/data/MST/MST-main/scripts/main_train.py", line 15, in <module>
    from mst.models.resnet import ResNet, ResNetSliceTrans
  File "/data/MST/MST-main/mst/models/__init__.py", line 3, in <module>
    from .mst_mamba_attn import MSTWithSparseFlashAttentionAndLMBlock
  File "/data/MST/MST-main/mst/models/mst_mamba_attn.py", line 3, in <module>
    from flash_attn.flash_attention import flash_attn_qkvpacked_func
ImportError: cannot import name 'flash_attn_qkvpacked_func' from 'flash_attn.flash_attention' (/root/miniconda3/lib/python3.10/site-packages/flash_attn/flash_attention.py)                                                                                         Thank you so so so so .....much!
