### ISSUE TITLE
There seems to be errors in a small number of elements of dk in flash-attention-2.

### ISSUE THREAD

**Issue by umiswing** [Dao-AILab/flash-attention#385]
Hello! I compare flash-attention-2 with a naive attention function in pytorch, and the following test script fails at dk's assert:
```python
import torch
import numpy as np
from flash_attn import flash_attn_func

def attention_naive(q, k, v, dropout_prob, scale):
    qt = torch.permute(q, [0, 2, 1, 3])
    kt = torch.permute(k, [0, 2, 1, 3])
    vt = torch.permute(v, [0, 2, 1, 3])
    scale = 1.0 / np.sqrt(q.shape[-1])
    s = torch.matmul(qt, torch.permute(kt, [0, 1, 3, 2]))
    s = s * scale

    s = torch.nn.functional.softmax(s,dim=-1, dtype=torch.float32).to(torch.float16)
    s = torch.matmul(s, vt)
    return torch.permute(s, [0, 2, 1, 3])

device = torch.device("cuda")
shape = (20, 1024, 20, 128)
dropout = 0.0
scale = 1.0 / np.sqrt(shape[-1])

np.random.seed(0)

query = np.random.random(shape)
q_ = torch.tensor(query, dtype=torch.float16, device=device)
q = torch.tensor(query, dtype=torch.float16, device=device)

key = np.random.random(shape)
k_ = torch.tensor(key, dtype=torch.float16, device=device)
k = torch.tensor(key, dtype=torch.float16, device=device)

value = np.random.random(shape)
v_ = torch.tensor(value, dtype=torch.float16, device=device)
v = torch.tensor(value, dtype=torch.float16, device=device)

q_.requires_grad = True
k_.requires_grad = True
v_.requires_grad = True

q.requires_grad = True
k.requires_grad = True
v.requires_grad = True

out_ = attention_naive(
    q_, k_, v_, dropout, scale)
out = flash_attn_func(q, k, v, dropout_p=dropout, softmax_scale=scale, causal=False)
np.testing.assert_allclose(out.detach().cpu().numpy(), out_.detach().cpu().numpy(), rtol=5e-03, atol=1e-03)

out_.backward(torch.ones_like(out_))
out.backward(torch.ones_like(out))
np.testing.assert_allclose(
    q.grad.cpu().numpy(), q_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
)
np.testing.assert_allclose(
    k.grad.cpu().numpy(), k_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
)
np.testing.assert_allclose(
    v.grad.cpu().numpy(), v_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
)
```
test output:
```bash
Traceback (most recent call last):
  File "torch_fa2_padded_verify.py", line 54, in <module>
    k.grad.cpu().numpy(), k_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
  ...

AssertionError:
Not equal to tolerance rtol=0.005, atol=0.001

Mismatched elements: 1540881 / 52428800 (2.94%)
Max absolute difference: 0.002502
Max relative difference: 21376.
 x: array([[[[-0.212   , -0.2069  , -0.2156  , ..., -0.2062  , -0.2051  ,
          -0.2134  ],
         [ 0.12067 ,  0.1243  ,  0.1276  , ...,  0.1248  ,  0.1316  ,...
 y: array([[[[-0.2115  , -0.2063  , -0.215   , ..., -0.2057  , -0.2046  ,
          -0.2129  ],
         [ 0.12085 ,  0.1245  ,  0.1277  , ...,  0.125   ,  0.1318  ,...
```
data type: float16 (Except that softmax is calculated with float32)
pytorch version: 1.12.0
flash-attention version: 2.0.1
gpu and cuda info: a100 and cuda 11.7

Is this calculation error as expected? What can cause this error?

**Comment by umiswing** [comment]
I think I made a mistake. I compute naive attention in fp32, and fa2 is able to pass all assertions, while following test shows that naive attention can't be computed in fp16:
```python
import torch
import numpy as np

def attention_naive(q, k, v, dropout_prob, scale):
    qt = torch.permute(q, [0, 2, 1, 3])
    kt = torch.permute(k, [0, 2, 1, 3])
    vt = torch.permute(v, [0, 2, 1, 3])
    scale = 1.0 / np.sqrt(q.shape[-1])
    s = torch.matmul(qt, torch.permute(kt, [0, 1, 3, 2]))
    s = s * scale

    s = torch.nn.functional.softmax(s,dim=-1, dtype=torch.float32).to(torch.float16)
    s = torch.matmul(s, vt)
    return torch.permute(s, [0, 2, 1, 3])

def attention_naive_fp32(q, k, v, dropout_prob, scale):
    qt = torch.permute(q, [0, 2, 1, 3])
    kt = torch.permute(k, [0, 2, 1, 3])
    vt = torch.permute(v, [0, 2, 1, 3])
    scale = 1.0 / np.sqrt(q.shape[-1])
    s = torch.matmul(qt, torch.permute(kt, [0, 1, 3, 2]))
    s = s * scale

    s = torch.nn.functional.softmax(s,dim=-1, dtype=torch.float32)
    s = torch.matmul(s, vt)
    return torch.permute(s, [0, 2, 1, 3])

device = torch.device("cuda")
shape = (20, 1024, 20, 128)
dropout = 0.0
scale = 1.0 / np.sqrt(shape[-1])

np.random.seed(0)

query = np.random.random(shape)
q_ = torch.tensor(query, dtype=torch.float32, device=device)
q = torch.tensor(query, dtype=torch.float16, device=device)

key = np.random.random(shape)
k_ = torch.tensor(key, dtype=torch.float32, device=device)
k = torch.tensor(key, dtype=torch.float16, device=device)

value = np.random.random(shape)
v_ = torch.tensor(value, dtype=torch.float32, device=device)
v = torch.tensor(value, dtype=torch.float16, device=device)

q_.requires_grad = True
k_.requires_grad = True
v_.requires_grad = True

q.requires_grad = True
k.requires_grad = True
v.requires_grad = True

out_ = attention_naive_fp32(
    q_, k_, v_, dropout, scale)
out = attention_naive(
    q, k, v, dropout, scale)
np.testing.assert_allclose(out.detach().cpu().numpy(), out_.detach().cpu().numpy(), rtol=5e-03, atol=1e-03)

out_.backward(torch.ones_like(out_))
out.backward(torch.ones_like(out))
np.testing.assert_allclose(
    q.grad.cpu().numpy(), q_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
)
np.testing.assert_allclose(
    k.grad.cpu().numpy(), k_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
)
np.testing.assert_allclose(
    v.grad.cpu().numpy(), v_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
)
```

output:
```bash
Traceback (most recent call last):
  File "torch_naive_fp16_fp32_verify.py", line 67, in <module>
    k.grad.cpu().numpy(), k_.grad.cpu().numpy(), rtol=5e-03, atol=1e-03
    ...

AssertionError:
Not equal to tolerance rtol=0.005, atol=0.001

Mismatched elements: 1558805 / 52428800 (2.97%)
Max absolute difference: 0.00260571
Max relative difference: 162853.22
 x: array([[[[-0.2115  , -0.2063  , -0.215   , ..., -0.2057  , -0.2046  ,
          -0.2129  ],
         [ 0.12085 ,  0.1245  ,  0.1277  , ...,  0.125   ,  0.1318  ,...
 y: array([[[[-0.212117, -0.20692 , -0.21556 , ..., -0.206266, -0.205154,
          -0.213468],
         [ 0.120624,  0.124268,  0.127449, ...,  0.12478 ,  0.131581,...
```

**Comment by tridao** [comment]
Glad it works out for you.
