### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2'

### ISSUE THREAD

**Issue by Luoxiaohei41** [Dao-AILab/flash-attention#396]
Help me,please.  it's too painful to match the environment！！！！

(FastChat) C:\Users\44557\FsChat\FastChat\scripts>pip install flash-attn==1.0.5
Collecting flash-attn==1.0.5
  Downloading flash_attn-1.0.5.tar.gz (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 1.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from flash-attn==1.0.5) (2.0.1+cu118)
Requirement already satisfied: einops in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from flash-attn==1.0.5) (0.6.1)
Requirement already satisfied: packaging in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from flash-attn==1.0.5) (23.1)
Collecting ninja (from flash-attn==1.0.5)
  Using cached ninja-1.11.1-py2.py3-none-win_amd64.whl (313 kB)
Requirement already satisfied: filelock in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from torch->flash-attn==1.0.5) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from torch->flash-attn==1.0.5) (4.7.1)
Requirement already satisfied: sympy in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from torch->flash-attn==1.0.5) (1.12)
Requirement already satisfied: networkx in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from torch->flash-attn==1.0.5) (3.1)
Requirement already satisfied: jinja2 in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from torch->flash-attn==1.0.5) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from jinja2->torch->flash-attn==1.0.5) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\44557\miniconda3\envs\fastchat\lib\site-packages (from sympy->torch->flash-attn==1.0.5) (1.3.0)
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for flash-attn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [134 lines of output]
      fatal: not a git repository (or any of the parent directories): .git

      Warning: Torch did not find available GPUs on this system.
       If your intention is to cross-compile, this is not an error.
      By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
      Volta (compute capability 7.0), Turing (compute capability 7.5),
      and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
      If you wish to cross-compile for a single specific architecture,
      export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

      torch.__version__  = 2.0.1+cpu

      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\attention_kernl.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\bert_padding.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attention.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attn_interface.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attn_triton.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attn_triton_og.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attn_triton_single_query.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attn_triton_tmp.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attn_triton_tmp_og.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_attn_triton_varlen.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_blocksparse_attention.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\flash_blocksparse_attn_interface.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\fused_softmax.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\rotary.py -> build\lib.win-amd64-cpython-38\flash_attn
      copying flash_attn\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn
      creating build\lib.win-amd64-cpython-38\flash_attn\layers
      copying flash_attn\layers\patch_embed.py -> build\lib.win-amd64-cpython-38\flash_attn\layers
      copying flash_attn\layers\rotary.py -> build\lib.win-amd64-cpython-38\flash_attn\layers
      copying flash_attn\layers\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn\layers
      creating build\lib.win-amd64-cpython-38\flash_attn\losses
      copying flash_attn\losses\cross_entropy.py -> build\lib.win-amd64-cpython-38\flash_attn\losses
      copying flash_attn\losses\cross_entropy_apex.py -> build\lib.win-amd64-cpython-38\flash_attn\losses
      copying flash_attn\losses\cross_entropy_parallel.py -> build\lib.win-amd64-cpython-38\flash_attn\losses
      copying flash_attn\losses\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn\losses
      creating build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\bert.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\gpt.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\gptj.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\gpt_j.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\gpt_neox.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\llama.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\opt.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\vit.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      copying flash_attn\models\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn\models
      creating build\lib.win-amd64-cpython-38\flash_attn\modules
      copying flash_attn\modules\block.py -> build\lib.win-amd64-cpython-38\flash_attn\modules
      copying flash_attn\modules\embedding.py -> build\lib.win-amd64-cpython-38\flash_attn\modules
      copying flash_attn\modules\mha.py -> build\lib.win-amd64-cpython-38\flash_attn\modules
      copying flash_attn\modules\mlp.py -> build\lib.win-amd64-cpython-38\flash_attn\modules
      copying flash_attn\modules\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn\modules
      creating build\lib.win-amd64-cpython-38\flash_attn\ops
      copying flash_attn\ops\activations.py -> build\lib.win-amd64-cpython-38\flash_attn\ops
      copying flash_attn\ops\fused_dense.py -> build\lib.win-amd64-cpython-38\flash_attn\ops
      copying flash_attn\ops\gelu_activation.py -> build\lib.win-amd64-cpython-38\flash_attn\ops
      copying flash_attn\ops\layer_norm.py -> build\lib.win-amd64-cpython-38\flash_attn\ops
      copying flash_attn\ops\rms_norm.py -> build\lib.win-amd64-cpython-38\flash_attn\ops
      copying flash_attn\ops\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn\ops
      creating build\lib.win-amd64-cpython-38\flash_attn\triton
      copying flash_attn\triton\fused_attention.py -> build\lib.win-amd64-cpython-38\flash_attn\triton
      copying flash_attn\triton\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn\triton
      creating build\lib.win-amd64-cpython-38\flash_attn\utils
      copying flash_attn\utils\benchmark.py -> build\lib.win-amd64-cpython-38\flash_attn\utils
      copying flash_attn\utils\distributed.py -> build\lib.win-amd64-cpython-38\flash_attn\utils
      copying flash_attn\utils\generation.py -> build\lib.win-amd64-cpython-38\flash_attn\utils
      copying flash_attn\utils\pretrained.py -> build\lib.win-amd64-cpython-38\flash_attn\utils
      copying flash_attn\utils\__init__.py -> build\lib.win-amd64-cpython-38\flash_attn\utils
      running build_ext
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2'
      Traceback (most recent call last):
        File "C:\Users\44557\miniconda3\envs\FastChat\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\44557\miniconda3\envs\FastChat\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\44557\miniconda3\envs\FastChat\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 163, in <module>
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\44557\AppData\Local\Temp\pip-build-env-f9npjefc\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects

**Comment by Luoxiaohei41** [comment]
gpu: rtx 4060 cuda 12.2 pytorch 2.0.1+cu118

**Comment by OrigamiDream** [comment]
Me either experiencing this issue on building Docker image of [HuggingFace TGI](https://github.com/huggingface/text-generation-inference)
