### ISSUE TITLE
ModuleNotFoundError: No module named 'flash_attn.flash_attention' Has the directory hierarchy changed in 2.0.4?

### ISSUE THREAD

**Issue by OliviaViessmann** [Dao-AILab/flash-attention#423]
Hi,

I just installed flash attention 2.0.4 and run into the error below. Has the directory hierarchy changed? Can this be fixed/reverted, or is this intended and I should reach out to the owners of the openfold package?
`Traceback (most recent call last):
  File "/home/pi-user/rlif/subprojects/moppo/./moppo_stab_acc_train.py", line 17, in <module>
    from rlif.tools.advantages import DeepStabPAdvantage, seq_recovery_advantage_fn
  File "/home/pi-user/rlif/rlif/tools/advantages.py", line 12, in <module>
    from rlif.folding_models.esmfold import ESMFoldModel
  File "/home/pi-user/rlif/rlif/folding_models/esmfold.py", line 2, in <module>
    from openfold.utils.feats import atom14_to_atom37
  File "/home/pi-user/miniconda3/envs/piai-rlif-cuda311/lib/python3.11/site-packages/openfold/__init__.py", line 1, in <module>
    from . import model
  File "/home/pi-user/miniconda3/envs/piai-rlif-cuda311/lib/python3.11/site-packages/openfold/model/__init__.py", line 11, in <module>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi-user/miniconda3/envs/piai-rlif-cuda311/lib/python3.11/site-packages/openfold/model/__init__.py", line 11, in <listcomp>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi-user/miniconda3/envs/piai-rlif-cuda311/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi-user/miniconda3/envs/piai-rlif-cuda311/lib/python3.11/site-packages/openfold/model/pair_transition.py", line 20, in <module>
    from openfold.model.primitives import Linear, LayerNorm
  File "/home/pi-user/miniconda3/envs/piai-rlif-cuda311/lib/python3.11/site-packages/openfold/model/primitives.py", line 28, in <module>
    from flash_attn.flash_attention import FlashAttention
ModuleNotFoundError: No module named 'flash_attn.flash_attention'`

Because when I do a simple import it looks like this:
`>>> import flash_attn as f
>>> dir(f)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'flash_attn_func', 'flash_attn_interface', 'flash_attn_kvpacked_func', 'flash_attn_qkvpacked_func', 'flash_attn_varlen_func', 'flash_attn_varlen_kvpacked_func', 'flash_attn_varlen_qkvpacked_func']`

Thanks

**Comment by DtYXs** [comment]
Same, hope the new version can be adapted to the previous `flash_attn.flash_attention`
