### ISSUE TITLE
fused_dense_lib compile fail under Rocky Linux 8.6 with gcc/g++ v8.5.0 installed

### ISSUE THREAD

**Issue by shanguanma** [Dao-AILab/flash-attention#497]
the error logger is as follows:
```[maduo@pbcmlg01 fused_dense_lib]$ gcc --version python setup.py install
No CUDA runtime is found, using CUDA_HOME='/cm/shared/apps/cuda11.8/toolkit/11.8.0'
running install
/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating fused_dense_lib.egg-info
writing fused_dense_lib.egg-info/PKG-INFO
writing dependency_links to fused_dense_lib.egg-info/dependency_links.txt
writing top-level names to fused_dense_lib.egg-info/top_level.txt
writing manifest file 'fused_dense_lib.egg-info/SOURCES.txt'
reading manifest file 'fused_dense_lib.egg-info/SOURCES.txt'
writing manifest file 'fused_dense_lib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'fused_dense_lib' extension
creating /mntnfs/lee_data1/maduo/codebase/flash-attention/csrc/fused_dense_lib/build
creating /mntnfs/lee_data1/maduo/codebase/flash-attention/csrc/fused_dense_lib/build/temp.linux-x86_64-cpython-39
/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Traceback (most recent call last):
  File "/mntnfs/lee_data1/maduo/codebase/flash-attention/csrc/fused_dense_lib/setup.py", line 26, in <module>
    setup(
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```
environment is as follows:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

```
```
gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
```
cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by akanyaani** [comment]
pip install -U flash-attn==2.0.8

**Comment by shanguanma** [comment]
> It seems your python may be too old? What version is it?

My python version : 3.9
```[maduo@pbcmlg01 fused_dense_lib]$ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by keyu-tian** [comment]
hi @shanguanma, have u solved this problem?

**Comment by luoyongjian1** [comment]
you should run it with one node with any gpu.I fix it in my slurm system.
