### ISSUE TITLE
ModuleNotFoundError: No module named 'flash_attn_cuda'

### ISSUE THREAD

**Issue by Lvjinhong** [Dao-AILab/flash-attention#535]
I am using NVIDIA's PyTorch docker: nvcr.io/nvidia/pytorch:23.08-py3. Inside it, flash-atten version 2.0.4 is already installed. Both nvcc and torch are based on CUDA 12.2. Unfortunately, I am encountering an error: No module named 'flash_attn_cuda'. How was this installed?

Additionally, I've heard that flash-atten does not support V100. I am currently using a machine with two V100 GPUs. At which step would this limitation manifest? Is the error I mentioned above related to this?

![image](https://github.com/Dao-AILab/flash-attention/assets/96970081/7f94864e-bd63-4a35-b358-0c3398a4d08f)

**Comment by tridao** [comment]
That module was from FlashAttention v1. You'd probably need to update (pip uninstall -y flash-attn, then reinstall).

In any case V100 isn't supported. It'll error when FlashAttention is called (not at import). Megatron has a flag to enable/disable FlashAttention.

**Comment by Lvjinhong** [comment]
> 该模块来自 FlashAttention v1。您可能需要更新（pip uninstall -y flash-attn，然后重新安装）。
> 
> 无论如何，V100 不受支持。调用 FlashAttention 时（而不是导入时）会出错。威震天有一个标志来启用/禁用 FlashAttention。
Thank you very much for your response. I understand that in the future, Flash2 will support architectures like 4090, but will it also support V100?

**Comment by tridao** [comment]
No we don't have concrete plan to work on V100.

**Comment by naveenfaclon** [comment]
when trying to install flash-attn facing this errr

ERROR: Command errored out with exit status 1:
     command: /home/naveen/Downloads/GIT/Phi3/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1fh91ee4/flash-attn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1fh91ee4/flash-attn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-1fh91ee4/flash-attn/pip-egg-info
         cwd: /tmp/pip-install-1fh91ee4/flash-attn/
    Complete output (19 lines):
    fatal: not a git repository (or any of the parent directories): .git
    /tmp/pip-install-1fh91ee4/flash-attn/setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1fh91ee4/flash-attn/setup.py", line 134, in <module>
        CUDAExtension(
      File "/home/naveen/Downloads/GIT/Phi3/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1077, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/home/naveen/Downloads/GIT/Phi3/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1204, in library_paths
        if (not os.path.exists(_join_cuda_home(lib_dir)) and
      File "/home/naveen/Downloads/GIT/Phi3/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2419, in _join_cuda_home
        raise OSError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    
    
    torch.__version__  = 2.3.0+cu121
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Seedmanc** [comment]
> That module was from FlashAttention v1. You'd probably need to update (pip uninstall -y flash-attn, then reinstall).
> 
> In any case V100 isn't supported. It'll error when FlashAttention is called (not at import). Megatron has a flag to enable/disable FlashAttention.

But I need FA 1, the 2nd ver. is not supported by my GPU.
