### ISSUE TITLE
Error installing flash-attn

### ISSUE THREAD

**Issue by trihardseven** [Dao-AILab/flash-attention#557]
Getting this error when trying to install:

C:\Users\Ncee>pip install flash-attn
Collecting flash-attn
  Using cached flash_attn-2.2.3.post2.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Ncee\AppData\Local\Temp\pip-install-_mpqxtbi\flash-attn_ef6e0c00497249169b0938c3e50ce866\setup.py", line 108, in <module>
          _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
        File "C:\Users\Ncee\AppData\Local\Temp\pip-install-_mpqxtbi\flash-attn_ef6e0c00497249169b0938c3e50ce866\setup.py", line 59, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
        File "C:\Users\Ncee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\Ncee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Ncee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Ncee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      torch.__version__  = 2.0.0+cu117

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Qubitium** [comment]
```pip install```  often error out for ```flash_attn``` for me due to various reasons. I have now resorted to only install via source and ```python setup.py install```.

**Comment by trihardseven** [comment]
> `pip install` often error out for `flash_attn` for me due to various reasons. I have now resorted to only install via source and `python setup.py install`.

I see, can you explain how to do that?

**Comment by tridao** [comment]
Windows probably won't work, we've only tested on Linux. Cutlass 3.2 should support Windows (it's what we've recently switched to) but it's likely we'll need more work to support Windows.
I recommend WSL for now.

**Comment by kalyani7195** [comment]
I am getting the same error -- even after using the setup.py -- any help would be greatly appreciated thank you!
<img width="959" alt="image" src="https://github.com/Dao-AILab/flash-attention/assets/13524848/0d392b36-7ec1-421e-873e-dc6b8f85f30c">

**Comment by Qubitium** [comment]
your stacktrace is showing nvcc not found errors. flash attn uses needs nvidia compiler to be propeely installed.

1. make sure you are not double installing nvcc from two diff pkg managers.
2. recommend getting clean python 3.11 env via miniconda but only use pip to install torch 2.2 and then flash attn. this will auto install nvcc.

**Comment by beam-hub** [comment]
I first run the command: pip install ninja, to install ninja, then i found the version at https://github.com/Dao-AILab/flash-attention/releases, download it and install it. The error was successfully resolved. Hope this works for you
