### ISSUE TITLE
[CE] error with triton-based `CrossEntropyLoss`

### ISSUE THREAD

**Issue by shijie-wu** [Dao-AILab/flash-attention#574]
We got the following error with the new triton-based `CrossEntropyLoss` during bf16 multi-gpu training.

## environment

```
# related pip package
triton                        2.0.0.dev20221202
torch                         2.0.1
flash-attn                    2.2.5

# nvcc version
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

## api call
```py
from flash_attn.losses.cross_entropy import (
    CrossEntropyLoss as FusedCrossEntropyLoss,
)
# ...
loss_fct = FusedCrossEntropyLoss(
    inplace_backward=True, process_group=None
)
# ...
loss = loss_fct(shift_logits, shift_labels)
```

## error
```
    File "<string>", line 21, in cross_entropy_fwd_kernel
  KeyError: ('2-.-0-.-0-83ca8b715a9dc5f32dc1110973485f64-2b0c5161c53c71b37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-d962222789c30252d492a16cca3bf467-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float32, torch.float32, torch.float32, torch.int64, 'fp32', 'fp32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (32768, False, False), (True, True, True, False, (False,), (False,), (False, False), (True, False), (True, False), (True, False), (False, False), (True, False)))
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
    File "/opt/ml/code/train_lib.py", line 682, in main
      total_steps, _, _ = train(
    File "/opt/ml/code/train_lib.py", line 243, in train
      loss = model(input_ids=input_ids, attention_mask=None, labels=labels)[
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
      result = forward_call(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 753, in forward
      output = self._fsdp_wrapped_module(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1504, in _call_impl
      return forward_call(*args, **kwargs)
    File "/opt/ml/code/modeling_llama_fast.py", line 336, in forward
      loss = loss_fct(shift_logits, shift_labels)
    File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1504, in _call_impl
      return forward_call(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/flash_attn-2.2.5-py3.10-linux-x86_64.egg/flash_attn/losses/cross_entropy.py", line 49, in forward
      loss = cross_entropy_loss(
    File "/opt/conda/lib/python3.10/site-packages/flash_attn-2.2.5-py3.10-linux-x86_64.egg/flash_attn/ops/triton/cross_entropy.py", line 285, in cross_entropy_loss
      return CrossEntropyLoss.apply(
    File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
      return super().apply(*args, **kwargs)  # type: ignore[misc]
    File "/opt/conda/lib/python3.10/site-packages/flash_attn-2.2.5-py3.10-linux-x86_64.egg/flash_attn/ops/triton/cross_entropy.py", line 174, in forward
      cross_entropy_fwd_kernel[(n_rows, n_splits)](
    File "/opt/conda/lib/python3.10/site-packages/triton/runtime/jit.py", line 106, in launcher
      return self.run(*args, grid=grid, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 200, in run
      return self.fn.run(*args, **kwargs)
    File "<string>", line 41, in cross_entropy_fwd_kernel
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 1256, in compile
      asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 892, in _compile
      module, _ = make_triton_ir(fn, signature, specialization, constants)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 842, in make_triton_ir
      raise e
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 838, in make_triton_ir
      generator.visit(fn.parse())
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
      return super().visit(node)
    File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
      return visitor(node)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 260, in visit_Module
      ast.NodeVisitor.generic_visit(self, node)
    File "/opt/conda/lib/python3.10/ast.py", line 420, in generic_visit
      self.visit(item)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
      return super().visit(node)
    File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
      return visitor(node)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 320, in visit_FunctionDef
      has_ret = self.visit_compound_statement(node.body)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 254, in visit_compound_statement
      self.last_ret = self.visit(stmt)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
      return super().visit(node)
    File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
      return visitor(node)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 479, in visit_If
      is_terminator = self.visit_compound_statement(node.orelse)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 254, in visit_compound_statement
      self.last_ret = self.visit(stmt)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
      return super().visit(node)
    File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
      return visitor(node)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 459, in visit_If
      cond = self.visit(node.test)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
      return super().visit(node)
    File "/opt/conda/lib/python3.10/ast.py", line 412, in visit
      return visitor(node)
    File "/opt/conda/lib/python3.10/site-packages/triton/compiler.py", line 775, in generic_visit
      raise NotImplementedError("Unsupported node: 
{}
".format(typename))
  NotImplementedError: Unsupported node: BoolOp
```

**Comment by tridao** [comment]
It probably works in triton 2.0 or triton 2.1.

**Comment by shijie-wu** [comment]
which version of triton would you recommend using? this docker file still points to `triton==2.0.0.dev20221202`
https://github.com/Dao-AILab/flash-attention/blob/601b4dc48dbe9d87c468daa2b4c0c8388b83753c/training/Dockerfile#L81

**Comment by tridao** [comment]
I've been using triton 2.1 these days.

**Comment by shijie-wu** [comment]
thank you! would you recommend installing via `pip install triton==2.1.0` or some nightly build? i am a bit confused since triton 2.1 is not tagged in the repo (https://github.com/openai/triton/issues/2407)

**Comment by tridao** [comment]
yeah `pip install triton==2.1.0` is how i did it.

**Comment by jkobject** [comment]
Hello @tridao,

seems related to #838. 
How would one go to use both flashattention2 with triton and the other triton functions in flash_attn?

**Comment by tridao** [comment]
You can use triton 2.1.0 or 2.2.0. I haven't touched https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_triton.py in a while. If you want to use it you'd likely need to fix some triton compatibility.
