### ISSUE TITLE
flash_attn_2_cuda missing

### ISSUE THREAD

**Issue by parham1998** [Dao-AILab/flash-attention#614]
I have an Nvidia Jetson Orin with jetpack 5.1.1, and I've upgraded manually to cuda 11.8 and cudnn 8.9.5.29. The wheel finishes successfully, but I get the following error while trying to import the following module:
**from flash_attn import flash_attn_qkvpacked_func, flash_attn_func**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orin/.local/lib/python3.8/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/orin/.local/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ModuleNotFoundError: No module named 'flash_attn_2_cuda'

```

**Comment by tridao** [comment]
Could be an issue with different python version. e.g you install to 1 python version (or conda env) and want to use it in another version (or conda env).
Other than that I don't know what the issue is.
