### ISSUE TITLE
error: command '/opt/linux/centos/8.x/x86_64/pkgs/cuda/11.7/bin/nvcc' failed with exit code 1

### ISSUE THREAD

**Issue by varuntrivedi18** [Dao-AILab/flash-attention#639]
Hello,
I am trying to install Flash Attention as a dependency for another tool "HyenaDNA" (https://github.com/HazyResearch/hyena-dna/tree/main). Upon cloning the Flash Attention repository and navigating to the `flash-attention` directory, I ran the command:-
 `pip install -U . --no-build-isolation`

and got the following output and error message:-

```
Processing /bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch in /bigdata/iwheeldonlab/vtriv002/conda/envs/hyena-dna/lib/python3.8/site-packages (from flash-attn==1.0.7) (1.13.0)
Requirement already satisfied: einops in /bigdata/iwheeldonlab/vtriv002/conda/envs/hyena-dna/lib/python3.8/site-packages (from flash-attn==1.0.7) (0.7.0)
Requirement already satisfied: packaging in /bigdata/iwheeldonlab/vtriv002/conda/envs/hyena-dna/lib/python3.8/site-packages (from flash-attn==1.0.7) (23.2)
Collecting ninja (from flash-attn==1.0.7)
  Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: typing_extensions in /bigdata/iwheeldonlab/vtriv002/conda/envs/hyena-dna/lib/python3.8/site-packages (from torch->flash-attn==1.0.7) (4.8.0)
Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for flash-attn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      
      Warning: Torch did not find available GPUs on this system.
       If your intention is to cross-compile, this is not an error.
      By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
      Volta (compute capability 7.0), Turing (compute capability 7.5),
      and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
      If you wish to cross-compile for a single specific architecture,
      export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.
      
      
      
      torch.__version__  = 1.13.0
      
      
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'flash_attn_cuda' extension
      gcc -pthread -B /rhome/vtriv002/.conda/envs/hyena-dna/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /rhome/vtriv002/.conda/envs/hyena-dna/include -fPIC -O2 -isystem /rhome/vtriv002/.conda/envs/hyena-dna/include -fPIC -I/bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn -I/bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src -I/bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/cutlass/include -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include/TH -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include/THC -I/opt/linux/centos/8.x/x86_64/pkgs/cuda/11.7/include -I/rhome/vtriv002/.conda/envs/hyena-dna/include/python3.8 -c csrc/flash_attn/fmha_api.cpp -o build/temp.linux-x86_64-cpython-38/csrc/flash_attn/fmha_api.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=flash_attn_cuda -D_GLIBCXX_USE_CXX11_ABI=0
      In file included from /bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src/fmha.h:42,
                       from csrc/flash_attn/fmha_api.cpp:33:
      /bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src/fmha_utils.h: In function ‘void set_alpha(uint32_t&, float, Data_type)’:
      /bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src/fmha_utils.h:63:56: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
               alpha = reinterpret_cast<const uint32_t &>( h2 );
                                                              ^
      /bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src/fmha_utils.h:68:56: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
               alpha = reinterpret_cast<const uint32_t &>( h2 );
                                                              ^
      /bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src/fmha_utils.h:70:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
               alpha = reinterpret_cast<const uint32_t &>( norm );
                                                                ^
      csrc/flash_attn/fmha_api.cpp: In function ‘void set_params_fprop(FMHA_fprop_params&, size_t, size_t, size_t, size_t, size_t, at::Tensor, at::Tensor, at::Tensor, at::Tensor, void*, void*, void*, void*, void*, float, float, bool, int)’:
      csrc/flash_attn/fmha_api.cpp:64:38: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct FMHA_fprop_params’; use assignment or value-initialization instead [-Wclass-memaccess]
           memset(&params, 0, sizeof(params));
                                            ^
      In file included from csrc/flash_attn/fmha_api.cpp:33:
      /bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src/fmha.h:75:8: note: ‘struct FMHA_fprop_params’ declared here
       struct FMHA_fprop_params : public Qkv_params {
              ^~~~~~~~~~~~~~~~~
      csrc/flash_attn/fmha_api.cpp:60:15: warning: unused variable ‘acc_type’ [-Wunused-variable]
           Data_type acc_type = DATA_TYPE_FP32;
                     ^~~~~~~~
      csrc/flash_attn/fmha_api.cpp: In function ‘std::vector<at::Tensor> mha_fwd(const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float, float, bool, bool, bool, int, c10::optional<at::Generator>)’:
      csrc/flash_attn/fmha_api.cpp:208:10: warning: unused variable ‘is_sm80’ [-Wunused-variable]
           bool is_sm80 = dprops->major == 8 && dprops->minor == 0;
                ^~~~~~~
      csrc/flash_attn/fmha_api.cpp: In function ‘std::vector<at::Tensor> mha_fwd_block(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float, float, bool, bool, c10::optional<at::Generator>)’:
      csrc/flash_attn/fmha_api.cpp:533:10: warning: unused variable ‘is_sm80’ [-Wunused-variable]
           bool is_sm80 = dprops->major == 8 && dprops->minor == 0;
                ^~~~~~~
      /opt/linux/centos/8.x/x86_64/pkgs/cuda/11.7/bin/nvcc -I/bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn -I/bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/src -I/bigdata/iwheeldonlab/vtriv002/hyena-dna/flash-attention/csrc/flash_attn/cutlass/include -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include/TH -I/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/include/THC -I/opt/linux/centos/8.x/x86_64/pkgs/cuda/11.7/include -I/rhome/vtriv002/.conda/envs/hyena-dna/include/python3.8 -c csrc/flash_attn/src/fmha_block_dgrad_fp16_kernel_loop.sm80.cu -o build/temp.linux-x86_64-cpython-38/csrc/flash_attn/src/fmha_block_dgrad_fp16_kernel_loop.sm80.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=flash_attn_cuda -D_GLIBCXX_USE_CXX11_ABI=0
      nvcc fatal   : Could not open output file '/scratch/vtriv002//tmpxft_001019e0_0000000a'
      No CUDA runtime is found, using CUDA_HOME='/opt/linux/centos/8.x/x86_64/pkgs/cuda/11.7'
      /rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      error: command '/opt/linux/centos/8.x/x86_64/pkgs/cuda/11.7/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects
```

I also tried running `python setup.py install` instead of the `pip install` command and ended up getting the same error.

My gcc version is 8.5.0 and CUDA version is 11.7.

Could someone please help me with this issue? Thank you.

**Comment by tridao** [comment]
Can you try just `pip install flash-attn`?

**Comment by varuntrivedi18** [comment]
I get a different error upon running `pip install flash-attn`. Output below:-

```
Collecting flash-attn
  Downloading flash_attn-2.3.3.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 10.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-s8fkc22a/flash-attn_3a23271825ee4031bb00f5ce993ce268/setup.py", line 18, in <module>
          import torch
        File "/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/__init__.py", line 191, in <module>
          _load_global_deps()
        File "/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/site-packages/torch/__init__.py", line 153, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/rhome/vtriv002/.conda/envs/hyena-dna/lib/python3.8/ctypes/__init__.py", line 373, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: libcublas.so.11: cannot open shared object file: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tridao** [comment]
Sounds like your environment doesn't have CUDA development libraries. You can try the nvcr pytorch docker [image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch).

**Comment by varuntrivedi18** [comment]
I discovered that I didn't have ninja, a required dependency for Flash Attention, installed earlier (the HyenaDNA README doesn't specify installing ninja as a pre-requisite to installing Flash Attention). Upon installing ninja, I could successfully install Flash Attention using `pip install flash-attn --no-build-isolation`.
However, the HyenaDNA README instructs users to install Flash Attention in editable mode. When I use the `-e` flag for installation, I get the following error message:-
`RuntimeError: Error compiling objects for extension`

Would I lose any functionality by not installing in editable mode?

**Comment by tridao** [comment]
> Would I lose any functionality by not installing in editable mode?

I don't think so.

**Comment by varuntrivedi18** [comment]
Thank you!
