### ISSUE TITLE
ERROR: Could not build wheels for dropout-layer-norm, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by vgoklani** [Dao-AILab/flash-attention#655]
Hey there,

We're unable to build the layer-norm extension.

We're using this docker image:

    nvcr.io/nvidia/pytorch:23.10-py3

and running this setup script:

    pip uninstall -y ninja && pip install ninja

    flash_attn_version=2.3.3

    pip install flash-attn==${flash_attn_version}

    cd

    # Install CUDA extensions for fused dense, layer norm
    git clone https://github.com/HazyResearch/flash-attention \
        && cd flash-attention && git checkout v${flash_attn_version} \
        && cd csrc/layer_norm && pip install . && cd ../../ \
        && cd csrc/fused_dense_lib && pip install . && cd ../../ \
        && cd .. && rm -rf flash-attention

taken from here:

    https://github.com/Dao-AILab/flash-attention/blob/main/training/Dockerfile#L91

Here is the stack-trace:

    https://gist.github.com/vgoklani/8be28099bd90991258fdb31f3f79b6b7

We've had this issue for a while and opened a ticket here:

    https://github.com/Dao-AILab/flash-attention/issues/587

Could you please us know whether you are planning to continue supporting the extensions or whether we should just remove them from our framework. thanks!

**Comment by tridao** [comment]
Can you try limiting MAX_JOBS?

**Comment by vgoklani** [comment]
@tridao thanks for the response; tried that, same response.

Also tried changing the repo to https://github.com/Dao-AILab/flash-attention

**Comment by tridao** [comment]
Yeah idk, I've built successfully with nvcr pytorch 23.10. The stack trace doesn't have any explicit error message pointing to a line in the code. If the layer_norm extension doesn't work for you then you don't have to use it.

**Comment by ZhenyuYangGithub** [comment]
> @tridao thanks for the response; tried that, same result.
> 
> ```
> flash_attn_version=2.3.3
> 
> pip install flash-attn==${flash_attn_version}
> 
> cd
> 
> # Install CUDA extensions for fused dense, layer norm
> git clone https://github.com/HazyResearch/flash-attention \
>     && cd flash-attention && git checkout v${flash_attn_version} \
>     && cd csrc/layer_norm && MAX_JOBS=4 pip install . && cd ../../ \
>     && cd csrc/fused_dense_lib && MAX_JOBS=4 pip install . && cd ../../ \
>     && cd .. && rm -rf flash-attention
> ```
> 
> Also tried changing the repo to https://github.com/Dao-AILab/flash-attention

Same issue here, have you managed to solve it?

**Comment by kingpingyue** [comment]
![QQ图片20231227140733](https://github.com/Dao-AILab/flash-attention/assets/47808999/16000994-cb78-4752-bd55-ed42bd97c71e)
请问这是什么原因

**Comment by gree2** [comment]
[34/57] /usr/local/cuda/bin/nvcc  -I/data/sda/deploy/qwen/flash-attention/csrc/layer_norm -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include/TH -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ailearn/.conda/envs/qwen/include/python3.10 -c -c /data/sda/deploy/qwen/flash-attention/csrc/layer_norm/ln_fwd_2560.cu -o /data/sda/deploy/qwen/flash-attention/csrc/layer_norm/build/temp.linux-x86_64-cpython-310/ln_fwd_2560.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=dropout_layer_norm -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/sda/deploy/qwen/flash-attention/csrc/layer_norm/setup.py", line 198, in <module>
          setup(
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dropout-layer-norm
  Running setup.py clean for dropout-layer-norm
Failed to build dropout-layer-norm
ERROR: Could not build wheels for dropout-layer-norm, which is required to install pyproject.toml-based projects

**Comment by gree2** [comment]
ERROR: Could not build wheels for dropout-layer-norm, which is required to install pyproject.toml-based projects
问题已解决：https://zhuanlan.zhihu.com/p/675270332

> [34/57] /usr/local/cuda/bin/nvcc -I/data/sda/deploy/qwen/flash-attention/csrc/layer_norm -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include/TH -I/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ailearn/.conda/envs/qwen/include/python3.10 -c -c /data/sda/deploy/qwen/flash-attention/csrc/layer_norm/ln_fwd_2560.cu -o /data/sda/deploy/qwen/flash-attention/csrc/layer_norm/build/temp.linux-x86_64-cpython-310/ln_fwd_2560.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=dropout_layer_norm -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17 ninja: build stopped: subcommand failed. Traceback (most recent call last): File "/home/ailearn/.conda/envs/qwen/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build subprocess.run( File "/home/ailearn/.conda/envs/qwen/lib/python3.10/subprocess.py", line 524, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/data/sda/deploy/qwen/flash-attention/csrc/layer_norm/setup.py", line 198, in setup( ... raise RuntimeError(message) from e RuntimeError: Error compiling objects for extension [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for dropout-layer-norm Running setup.py clean for dropout-layer-norm Failed to build dropout-layer-norm ERROR: Could not build wheels for dropout-layer-norm, which is required to install pyproject.toml-based projects

**Comment by AllenShow** [comment]
> https://zhuanlan.zhihu.com/p/675270332

失效了，怎么解决的？
