### ISSUE TITLE
Undefined symbol: _ZNK3c106SymIntltEl

### ISSUE THREAD

**Issue by mhillebrand** [Dao-AILab/flash-attention#667]
Whether I try to use flash attention or not, just having it installed yields the following error:

`ImportError: /home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl`

Linux Mint (latest)
Python 3.11.4
PyTorch 2.1.0
CUDA 12.1.1
Transformers 4.35.0

Any suggestions?

Here's the full trace:

```
Traceback (most recent call last):
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1345, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/models/mistral/modeling_mistral.py", line 47, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/topics/topic_generator.py", line 85, in <module>
    topic_generator = TopicGenerator()
                      ^^^^^^^^^^^^^^^^
  File "/home/matt/mr/engine/utilz/common.py", line 92, in time_closure
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/topics/topic_generator.py", line 18, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 387, in _get_model_class
    supported_models = model_mapping[type(config)]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 740, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 754, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 698, in getattribute_from_module
    if hasattr(module, attr):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1335, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1347, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.mistral.modeling_mistral because of the following error (look up to see its traceback):
/home/matt/miniconda3/envs/nlp/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl
```

**Comment by tridao** [comment]
HF is probably trying to import it. Probably have to do with pytorch version etc.
Worst case, you can uninstall flashattention if it doesn't work for you

**Comment by tridao** [comment]
I think 2.1.0 should also work.

**Comment by tridao** [comment]
Did you install FlashAttention from PyPI (e.g with pip install flash-attn) or from source?

**Comment by smidtfab** [comment]
I am encountering something similar. I am guessing it has to do with incompatibilities. I tried to install it from PyPi as well as the source.

Python 3.8.10
PyTorch 2.1.0
CUDA 12.1
Transformers 4.34.0

> Traceback (most recent call last):
  File "finetuning.py", line 48, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/x_fschm/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "/home/x_fschm/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 387, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/home/x_fschm/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 739, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/home/x_fschm/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 753, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/home/x_fschm/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 697, in getattribute_from_module
    if hasattr(module, attr):
  File "/home/x_fschm/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/x_fschm/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/home/x_fschm/.local/lib/python3.8/site-packages/flash_attn_2_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl

**Comment by smidtfab** [comment]
I fixed the issue by downgrading the dependencies. (Note that some of the dependencies might be obsolete.)

> --extra-index-url https://download.pytorch.org/whl/cu118
torch==2.0.1+cu118
transformers==4.31.0
datasets==2.13.0
peft==0.4.0
accelerate==0.21.0
bitsandbytes==0.40.2 
trl==0.4.7 
safetensors>=0.3.1

**Comment by gdippolito** [comment]
Just for future reference I got the same exact issue when I used a flash attention (2.3.3) wheel compiled from source. 
In my case the issue was caused by the wheel being compiled with Pytorch 2.0.1 but then used in an environment with Pytorch 2.1.1. 
Hope it helps anyone facing the same problem.

**Comment by Tsukumizu** [comment]
uninstall torch==2.1.0 then install torch==2.0.1.  It works for me.

**Comment by samikrc** [comment]
I got this error as well. Couldn't resolve it by just switching to 2.3.5. I ended up compiling the 2.3.5 branch and installing, using `python setup.py install`, as per instructions at `https://github.com/Dao-AILab/flash-attention/tree/v2.3.5`. On second thoughts, I probably should have been successful compiling 2.3.6 as well. Will try.

**Comment by amsword** [comment]
also hit the issues with pytorch 2.1; switching back to 2.0 works, though.

**Comment by 0010SS** [comment]
Same for me. I downgraded to PyTorch 2.0 from 2.1 and solved the issue.

**Comment by Emplemon** [comment]
why? I downgraded to PyTorch 2.0 from 2.2, still no useful? 
lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by kenning** [comment]
on a new runpod vm (the "pytorch 2.4.0" docker image, which is pretty bare bones) i got flash-attn installed with:

* flash-attn==2.7.3
* torch==2.5.1
* cuda V12.4.131
* python 3.11.10

**Comment by HaiFangfang** [comment]
maybe make sure that the cuda version and torch version of flash-attn matches running cuda and torch helps. 

I was using:
flash-attn==2.2.0
torch 2.1.1
python 3.11.11
cuda V12.1.666

at first I installed flash-attn2.2.0+cu _118_ torch _2.0_ cxx11abiFALSE-cp311-cp311-linux_x86_64.whl
but then I updated cuda from 11.8 to 12.1, torch from 2.1.0 to 2.1.1, then I met exactly the same error `flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl`

I noticed that it might be the mismatch of cuda version and again installed flash-attn2.2.0+cu _121_ torch _2.1_cxx11abiFALSE-cp311-cp311-linux_x86_64.whl. This time it works.
Note that must uninstall the old flash-attn2.2.0+cu _118_ torch _2.1_cxx11abiFALSE-cp311-cp311-linux_x86_64.whl first, if not, pip may not install the new flash-attn pack with the same version 2.2.0

No need to downgrade pytorch. Hope this helps.

**Comment by yuanllong** [comment]
https://blog.csdn.net/a61022706/article/details/141570792  这个可以解决

**Comment by Symbolk** [comment]
As mentioned by yuanllong, reinstall flash_attn with exactly matched versions solves it:
```
pip uninstall flash-attn -y

# get 3 version numbers
python -V
nvcc -V
pip show torch

# download exactly matched whl here: https://github.com/Dao-AILab/flash-attention/releases
# install it!
pip install *.whl
```
