### ISSUE TITLE
Undefined symbol with pre-built cuda wheel on pytorch:23.11-py3

### ISSUE THREAD

**Issue by jlamypoirier** [Dao-AILab/flash-attention#709]
I am getting an undefined symbol error when running flash_attn 2.3.6 installed through pip in the latest release of nvidia-pytorch-docker (the recommended base image), nvcr.io/nvidia/pytorch:23.11-py3:
```
$ pip install flash-attn --no-build-isolation --upgrade
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: flash-attn in /usr/local/lib/python3.10/dist-packages (2.0.4)
Collecting flash-attn
[...]
Successfully installed flash-attn-2.3.6
$ python3 -c "import flash_attn"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.local/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/tmp/.local/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /tmp/.local/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1017SymbolicShapeMeta18init_is_contiguousEv
```
The same works when I build the wheel myself, so I guessing it's a version issue? (both torch and cuda versions changed compared to 23:10)

**Comment by chinoll** [comment]
same question

**Comment by Avelina9X** [comment]
same issue here with the 23.11-py3 docker container

**Comment by hijkzzz** [comment]
same issue

**Comment by tridao** [comment]
It's because of torch version change. nvcr pytorch 23.12 should work with flash-attn v2.4.0.post1 now.
