### ISSUE TITLE
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by urec56** [Dao-AILab/flash-attention#749]
I tried to install codellama 13B version, then got error that I missed flash-attention. When I tried to install it with pip, I got this
```
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      
      
      torch.__version__  = 2.1.2+rocm5.6
      
      
      running bdist_wheel
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ra0rdwg0/flash-attn_57ed3f11ae184b1485e4ab15677f36f5/setup.py", line 285, in <module>
          setup(
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/setuptools/__init
__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-ra0rdwg0/flash-attn_57ed3f11ae184b1485e4ab15677f36f5/setup.py", line 262, in run
          wheel_url, wheel_filename = get_wheel_url()
                                      ^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ra0rdwg0/flash-attn_57ed3f11ae184b1485e4ab15677f36f5/setup.py", line 231, in get_wheel_url
          torch_cuda_version = parse(torch.version.cuda)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
          return Version(version)
                 ^^^^^^^^^^^^^^^^
        File "/home/urec/Downloads/all/other/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
          match = self._regex.search(version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: expected string or bytes-like object, got 'NoneType'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects
```

nvcc:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
```
pip: 23.3.1 - latest
Python: 3.11.5
GPU: AMD Radeon RX 6700 XT
system: archlinux latest

Maybe it's because of the AMD GPU?

**Comment by tridao** [comment]
Yes, as mentioned in the README only Nvidia GPUs are supported.
