### ISSUE TITLE
[Bug] Undefined symbol when executing `import flash_attn` after installing on recommended NVIDIA container

### ISSUE THREAD

**Issue by jaanli** [Dao-AILab/flash-attention#809]
Any ideas on how to debug this? 

Running into a bug when installing this on Amazon Web Services `g5.xlarge` instances on EC2 with A10 GPUs that should support the `flash_attn` library: 

```
>>> import flash_attn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15sum_IntList_out4callERKNS_6TensorEN3c1016OptionalArrayRefIlEEbSt8optionalINS5_10ScalarTypeEERS2_
>>> 
```

This is using the recommended NVIDIA container:
* https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

The following commands can be executed in this container to reproduce this bug: 
```
docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:23.11-py3
pip uninstall flash_attn  # uninstall the older 2.0.2 version of flash_attn that ships with the container
MAX_JOBS=4 pip install flash-attn --no-build-isolation 
python
>>> import flash_attn
```

Thank you so much for this library! :) Really excited to test it for our research in the health care + LLM domain 🙏

**Comment by tridao** [comment]
Try flash-attn=2.5.1? nvcr now uses pytorch 2.2.0.dev20231106 but our CI now compiles for torch 2.2.0 official, and the wheel compiled for the 2 versions are not compatible.

**Comment by jaanli** [comment]
On it, thank you so much -- you and your lab rock Tri!

**Comment by jaanli** [comment]
Okay, that worked! Thank you @tridao :) 

```
docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:24.01-py3
pip install flash-attn==2.5.1.post1 --no-build-isolation
``` 

However, I'm finding that I need to increase the tolerance to be quite high (`0.2`) when testing the forward and backward passes for shorter sequence lengths -- and that the sign of the gradients differs between the PyTorch `F.scaled_dot_product_attention` ([docs](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html)).

Is this normal/expected? 

Also, the memory savings are amazing: able to scale to `2**19` or a context length of 524288 tokens on a single A10 GPU with ~20GB memory before getting an out-of-memory error!

Though I am curious about the speed trade-off for longer sequence lengths: fast attention yields a 45x speedup on the forward pass but it 60% slowdown compared to the `F.scaled_dot_product_attention` PyTorch function (for sequence lengths of 128), so there might be some architectures/edge cases/sequence lengths for which it could make sense to use one vs the other.

Happy to start another thread if easier and close this one out (this is likely unrelated to `flash-attn==2.5.1.post1`).

Testing script: 

https://gist.github.com/jaanli/c42db1454f540171516ffae08e8d9454

Example output: 
```
python test_flash_bw.py
Flash Attention Forward Duration: 0.002987 seconds
PyTorch Scaled Dot Product Attention Forward Duration: 0.090282 seconds
Flash Attention Backward Duration: 0.015947 seconds
PyTorch Scaled Dot Product Attention Backward Duration: 0.009706 seconds
Flash Attention Output (sample): tensor([0.5000, 0.5000, 0.5000, 0.4980, 0.4980, 0.5000, 0.5039, 0.5000, 0.5000,
        0.4980, 0.5000, 0.4961, 0.5000, 0.5000, 0.5000, 0.4980, 0.5000, 0.5000,
        0.5000, 0.5039, 0.5000, 0.5000, 0.5000, 0.5000, 0.5039, 0.5000, 0.5000,
        0.5000, 0.5000, 0.5039, 0.5000, 0.5000, 0.5039, 0.5039, 0.5000, 0.5000,
        0.5000, 0.4980, 0.4980, 0.5039, 0.5000, 0.4980, 0.4980, 0.4980, 0.5000,
        0.5039, 0.4980, 0.5000, 0.4961, 0.5000, 0.4980, 0.5000, 0.5000, 0.4980,
        0.5000, 0.5039, 0.5000, 0.5000, 0.5039, 0.5039, 0.5000, 0.4980, 0.5000,
        0.5000], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<SelectBackward0>)
PyTorch Scaled Dot Product Attention Output (sample): tensor([0.4980, 0.5000, 0.5000, 0.5000, 0.5039, 0.5000, 0.5039, 0.5000, 0.4980,
        0.5000, 0.5000, 0.5039, 0.5039, 0.4961, 0.5000, 0.4980, 0.5000, 0.4961,
        0.4980, 0.5039, 0.4980, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
        0.5000, 0.5000, 0.5039, 0.5000, 0.5000, 0.5000, 0.5039, 0.5039, 0.5000,
        0.5039, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.4961,
        0.4980, 0.5000, 0.4961, 0.4961, 0.5000, 0.4980, 0.4941, 0.5039, 0.5000,
        0.5000, 0.4980, 0.5000, 0.5000, 0.5039, 0.5039, 0.4980, 0.5000, 0.5039,
        0.5000], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<SelectBackward0>)
All output elements are within the specified tolerance.
All gradient elements are within the specified tolerance.
Flash Attention Grad (sample): tensor([-3.1650e-10, -3.5925e-11, -2.1828e-10, -4.3656e-10,  2.8740e-10,
        -5.4342e-11,  2.4784e-11,  4.6612e-11, -3.0013e-10, -2.8558e-10,
        -3.0741e-10,  1.7008e-10, -1.6371e-10,  2.8922e-10, -3.1650e-10,
        -4.0927e-10,  3.1605e-11, -2.4784e-11, -4.8658e-11, -3.8017e-10,
         5.4570e-11, -7.1850e-11,  1.0141e-10, -1.2187e-10, -1.2005e-10,
        -3.4925e-10, -1.8372e-10,  2.8422e-11, -4.4338e-11, -5.1296e-10,
        -5.0568e-10, -3.4743e-10, -6.5484e-10,  5.5252e-11, -2.6921e-10,
        -5.7526e-11,  8.1400e-11,  1.1505e-10, -8.8676e-11, -1.3370e-10,
         4.8885e-11, -1.6735e-10, -1.6371e-10, -5.1159e-11, -2.9286e-10,
        -3.9654e-10, -7.6398e-11, -1.7917e-10,  9.5042e-11,  1.9463e-10,
        -1.3245e-11,  4.4020e-10, -4.5839e-10,  3.7744e-11, -7.1395e-11,
         7.4124e-11, -8.2309e-11, -1.4779e-11, -1.8554e-10, -2.8558e-10,
         1.7280e-10, -7.6852e-11, -6.3665e-11, -3.8017e-10], device='cuda:0',
       dtype=torch.bfloat16)
PyTorch Scaled Dot Product Attention Grad (sample): tensor([ 2.0373e-10, -1.5098e-10,  6.6393e-11, -1.0232e-10, -1.3188e-10,
         1.7099e-10,  9.5497e-11,  2.2919e-10,  3.1469e-10,  3.0013e-10,
         1.3824e-10,  2.9104e-10, -9.8225e-11,  8.2309e-11, -3.7835e-10,
        -4.7748e-11, -1.7644e-10,  1.5802e-11,  5.6843e-11,  1.8645e-10,
        -2.3829e-10,  1.0687e-10,  2.8376e-10,  6.7303e-11,  2.2101e-10,
         2.4556e-10,  1.8827e-10, -5.3205e-11, -3.0923e-11, -2.1487e-11,
        -8.9130e-11, -3.9836e-10, -1.1710e-11, -7.5488e-11,  7.0031e-11,
        -6.0481e-11,  6.2300e-11,  2.7649e-10,  6.0027e-11,  7.7307e-12,
         1.2005e-10, -2.3647e-10,  1.7167e-11, -1.3824e-10,  2.7649e-10,
         4.6566e-10,  2.2101e-10,  1.8099e-10,  2.7285e-10,  3.8744e-10,
         1.1642e-10,  2.7467e-10, -2.4011e-10, -1.3006e-10,  7.8217e-11,
         4.3838e-10,  1.4097e-10, -7.0486e-11,  2.8194e-10,  1.2642e-10,
         2.4738e-10, -2.7831e-10,  1.3279e-10, -7.1395e-11], device='cuda:0',
       dtype=torch.bfloat16)
```

**Comment by tridao** [comment]
Try comparing (standard attn in fp32 - standard attn in bf16) to get a sense of the scale of numerical error.

**Comment by jaanli** [comment]
Will do! Thank you again Tri!

**Comment by KAIWEILIUCC** [comment]
> Try flash-attn=2.5.1? nvcr now uses pytorch 2.2.0.dev20231106 but our CI now compiles for torch 2.2.0 official, and the wheel compiled for the 2 versions are not compatible.

That work! Thank you.

**Comment by pk315** [comment]
my issue pytorch 2.6 cu12.4 flash-attn 2.8.3 will occurs the issue on the ubuntu 22
but when upgrade the  torch to cu12.8 , pytorch 2.9 +cu12.8 +cuda 12.8 it works for flash-attn2.8.3 . 
hope it will help you.
