### ISSUE TITLE
`2.5.0` has an issue accessing memory illegally during backward

### ISSUE THREAD

**Issue by seungduk-yanolja** [Dao-AILab/flash-attention#812]
https://github.com/Dao-AILab/flash-attention/issues/338
The same issue is reproduced.

```sh
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/axo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/miniconda3/envs/axo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/apps/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/apps/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/home/user/apps/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/home/user/apps/axolotl/src/axolotl/train.py", line 167, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/transformers/trainer.py", line 1561, in train
    return inner_training_loop(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/transformers/trainer.py", line 1893, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/transformers/trainer.py", line 2822, in training_step
    self.accelerator.backward(loss)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/accelerator.py", line 1964, in backward
    loss.backward(**kwargs)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 288, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 318, in backward
    _flash_attn_varlen_backward(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 179, in _flash_attn_varlen_backward
    dq, dk, dv, softmax_d, = flash_attn_cuda.varlen_bwd(
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I tested various combinations such as `transformers==4.37.2` and `transformers-4.38.0.dev0` with `flash-attn` versions `2.5.2`, `2.5.0`, `2.4.3.post1`, and `2.4.2`.`2.4.3.post1` and `2.4.2` do not have the issue, while `2.5.2` and `2.5.0` had the issue.For the same dataset, it consistently occurred at the 46th global step. No other datasets were tested yet.

**Comment by tridao** [comment]
Can you save the tensors being passed to flash_attn_cuda.varlen_bwd and send them to me? Otherwise it would be very hard to debug?

And can you print out the value of cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k, and the shape of q, k, v?

**Comment by tridao** [comment]
Can you save the tensors being passed to flash_attn_cuda.varlen_bwd and send them to me? Otherwise it would be very hard to debug?

And can you print out the value of cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k, and the shape of q, k, v?

**Comment by seungduk-yanolja** [comment]
I tried to save the tensors when it happened but it was challenging and I failed.
One thing I can tell is that it happens when I modify the gradients using the hook as explained here:
https://huggingface.co/yanolja/KoSOLAR-10.7B-v0.2#technical-deep-dive

**Comment by tridao** [comment]
Would be hard for me to debug if I can't reproduce it. You can do try catch to hopefully save the tensors.

**Comment by leasunhy** [comment]
Same here. Please kindly use the tensors [here](https://github.com/leasunhy/fa2-curious-case) to reproduce the issue.

* 2.5.8: invalid memory access
* 2.4.3.post1: run without issue

**Comment by sfc-gh-bzhai** [comment]
Same here, and the weird part is if I using the datasets with load_dataset, it can run without issue, but if I use local dataset which loaded by load_from_disk, it will trigger this issue.
