### ISSUE TITLE
Error with triton

### ISSUE THREAD

**Issue by pipijing13** [Dao-AILab/flash-attention#838]
I was trying to use the training scripts you provided to train GPT2, and the following is the error I met related with triton. I was using 1 A100-80G, with the command:
**python run.py experiment=owt/gpt2s-flash trainer.devices=1**

### environment
triton                        2.0.0.dev20221202 or 2.0.1
torch                         1.13.1
flash-attn                    2.5.3

Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

### error

**If I use triton==2.0.1, I got following error message**

[2024-02-19 13:56:02,656][pytorch_lightning.accelerators.cuda][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
[2024-02-19 13:56:02,660][src.tasks.seq][INFO] - Optimizer group 0: 0 tensors, 0 parameters, {'weight_decay': 0.1, 'lr': 0.0006, 'bias_correction': True, 'betas': (0.9, 0.999), 'eps': 1e-08}
[2024-02-19 13:56:02,661][src.tasks.seq][INFO] - Optimizer group 1: 100 tensors, 39510528 parameters, {'weight_decay': 0.0, 'lr': 0.0006, 'bias_correction': True, 'betas': (0.9, 0.999), 'eps': 1e-08}
[2024-02-19 13:56:02,661][src.tasks.seq][INFO] - Optimizer group 2: 48 tensors, 84934656 parameters, {'lr_multiplier': 1.0, 'lr': 0.0006, 'bias_correction': True, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0.1}
┏━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃   ┃ Name          ┃ Type             ┃ Params ┃
┡━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ model         │ GPTLMHeadModel   │  124 M │
│ 1 │ loss_fn       │ CrossEntropyLoss │      0 │
│ 2 │ loss_fn_val   │ CrossEntropyLoss │      0 │
│ 3 │ train_metrics │ MetricCollection │      0 │
│ 4 │ val_metrics   │ MetricCollection │      0 │
│ 5 │ test_metrics  │ MetricCollection │      0 │
└───┴───────────────┴──────────────────┴────────┘
Trainable params: 124 M                                                                                                                                     
Non-trainable params: 0                                                                                                                                     
Total params: 124 M                                                                                                                                         
Total estimated model params size (MB): 248                                                                                                                 
Sanity Checking DataLoader 0:   0%|                                                                                                   | 0/2 [00:00<?, ?it/s]sh: /tmp:/compile-ptx-log-038b02: No such file or directory
Error executing job with overrides: ['experiment=owt/gpt2s-flash', 'trainer.devices=1']
Traceback (most recent call last):
  File "/projects/lyang28/ys/reliability/flash-attention/training/run.py", line 68, in <module>
    main()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/projects/lyang28/ys/reliability/flash-attention/training/run.py", line 62, in main
    return train(config)
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/train.py", line 111, in train
    trainer.fit(model=model, datamodule=datamodule, **ckpt_cfg)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1153, in _run_train
    self._run_sanity_check()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1225, in _run_sanity_check
    val_loop.run()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/tasks/seq.py", line 121, in validation_step
    return self.shared_step(batch, batch_idx, phase='val')
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/tasks/seq.py", line 180, in shared_step
    loss, output, targets = self.step(batch, is_train=(phase == 'train'))
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/tasks/seq.py", line 173, in step
    output = self.forward(x).logits
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/tasks/seq.py", line 91, in forward
    return self.model(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/models/gpt.py", line 646, in forward
    hidden_states = self.transformer(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/models/gpt.py", line 539, in forward
    hidden_states, residual = layer(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/modules/block.py", line 142, in forward
    hidden_states, residual = layer_norm_fn(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/ops/triton/layer_norm.py", line 875, in layer_norm_fn
    return LayerNormFn.apply(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/ops/triton/layer_norm.py", line 748, in forward
    y, y1, mean, rstd, residual_out, seeds, dropout_mask, dropout_mask1 = _layer_norm_fwd(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/ops/triton/layer_norm.py", line 335, in _layer_norm_fwd
    _layer_norm_fwd_1pass_kernel[(M,)](
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/testing.py", line 104, in do_bench
    fn()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 81, in kernel_call
    self.fn.run(*args, num_warps=config.num_warps, num_stages=config.num_stages, **current)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 232, in run
    return self.fn.run(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 232, in run
    return self.fn.run(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 232, in run
    return self.fn.run(*args, **kwargs)
  File "<string>", line 63, in _layer_norm_fwd_1pass_kernel
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler/compiler.py", line 476, in compile
    next_module = compile_kernel(module)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler/compiler.py", line 351, in <lambda>
    lambda src: ptx_to_cubin(src, arch))
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler/compiler.py", line 150, in ptx_to_cubin
    return compile_ptx_to_cubin(ptx, ptxas, arch)
RuntimeError: `ptxas` failed with error code 1: 

**And if I use triton==2.0.0.dev20221202, I got following error message**

[2024-02-19 13:46:16,164][src.train][INFO] - Starting training!
[2024-02-19 13:46:16,172][src.utils.utils][INFO] - Load from cache at /projects/lyang28/ys/reliability/flash-attention/training/data/openwebtext/cache/tokenizer_name-gpt2-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False
[2024-02-19 13:46:16,235][src.utils.utils][INFO] - Load from cache at /projects/lyang28/ys/reliability/flash-attention/training/data/openwebtext/cache/tokenizer_name-gpt2-val_ratio-0.0005-val_split_seed-2357-add_eos-True-detokenize-False
[2024-02-19 13:46:17,343][pytorch_lightning.accelerators.cuda][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
[2024-02-19 13:46:17,347][src.tasks.seq][INFO] - Optimizer group 0: 0 tensors, 0 parameters, {'weight_decay': 0.1, 'lr': 0.0006, 'bias_correction': True, 'betas': (0.9, 0.999), 'eps': 1e-08}
[2024-02-19 13:46:17,347][src.tasks.seq][INFO] - Optimizer group 1: 100 tensors, 39510528 parameters, {'weight_decay': 0.0, 'lr': 0.0006, 'bias_correction': True, 'betas': (0.9, 0.999), 'eps': 1e-08}
[2024-02-19 13:46:17,347][src.tasks.seq][INFO] - Optimizer group 2: 48 tensors, 84934656 parameters, {'lr_multiplier': 1.0, 'lr': 0.0006, 'bias_correction': True, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0.1}
┏━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃   ┃ Name          ┃ Type             ┃ Params ┃
┡━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ model         │ GPTLMHeadModel   │  124 M │
│ 1 │ loss_fn       │ CrossEntropyLoss │      0 │
│ 2 │ loss_fn_val   │ CrossEntropyLoss │      0 │
│ 3 │ train_metrics │ MetricCollection │      0 │
│ 4 │ val_metrics   │ MetricCollection │      0 │
│ 5 │ test_metrics  │ MetricCollection │      0 │
└───┴───────────────┴──────────────────┴────────┘
Trainable params: 124 M                                                                                                                                     
Non-trainable params: 0                                                                                                                                     
Total params: 124 M                                                                                                                                         
Total estimated model params size (MB): 248                                                                                                                 
Sanity Checking DataLoader 0:   0%|                                                                                                   | 0/2 [00:00<?, ?it/s]Error executing job with overrides: ['experiment=owt/gpt2s-flash', 'trainer.devices=1']
Traceback (most recent call last):
  File "<string>", line 21, in cross_entropy_fwd_kernel
KeyError: ('2-.-0-.-0-7d1eb0d2fed8ff2032dccb99c2cc311a-2b0c5161c53c71b37ae20a9996ee4bb8-c1f92808b4e4644c1732e8338187ac87-d962222789c30252d492a16cca3bf467-12f7ac1ca211e037f62a7c0c323d9990-5c5e32ff210f3b7f56c98ca29917c25e-06f0df2d61979d629033f4a22eff5198-0dd03b0bd512a184b3512b278d9dfa59-d35ab04ae841e2714a253c523530b071', (torch.float32, torch.float32, torch.float32, torch.float16, torch.int64, 'fp32', 'fp32', 'fp32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (65536, False, False), (True, True, True, True, True, (False,), (False,), (False,), (False, False), (False, False), (True, False), (False, False), (True, False), (False, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/lyang28/ys/reliability/flash-attention/training/run.py", line 68, in <module>
    main()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/projects/lyang28/ys/reliability/flash-attention/training/run.py", line 62, in main
    return train(config)
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/train.py", line 111, in train
    trainer.fit(model=model, datamodule=datamodule, **ckpt_cfg)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1153, in _run_train
    self._run_sanity_check()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1225, in _run_sanity_check
    val_loop.run()
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/tasks/seq.py", line 121, in validation_step
    return self.shared_step(batch, batch_idx, phase='val')
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/tasks/seq.py", line 180, in shared_step
    loss, output, targets = self.step(batch, is_train=(phase == 'train'))
  File "/projects/lyang28/ys/reliability/flash-attention/training/src/tasks/seq.py", line 176, in step
    loss = self.loss_fn(output, y) if is_train else self.loss_fn_val(output, y)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/losses/cross_entropy.py", line 57, in forward
    loss, z_loss = cross_entropy_loss(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/ops/triton/cross_entropy.py", line 311, in cross_entropy_loss
    return CrossEntropyLoss.apply(
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/flash_attn-2.5.3-py3.10-linux-x86_64.egg/flash_attn/ops/triton/cross_entropy.py", line 186, in forward
    cross_entropy_fwd_kernel[(n_rows, n_splits)](
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 200, in run
    return self.fn.run(*args, **kwargs)
  File "<string>", line 41, in cross_entropy_fwd_kernel
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 1256, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 892, in _compile
    module, _ = make_triton_ir(fn, signature, specialization, constants)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 842, in make_triton_ir
    raise e
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 838, in make_triton_ir
    generator.visit(fn.parse())
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 260, in visit_Module
    ast.NodeVisitor.generic_visit(self, node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 320, in visit_FunctionDef
    has_ret = self.visit_compound_statement(node.body)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 254, in visit_compound_statement
    self.last_ret = self.visit(stmt)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 479, in visit_If
    is_terminator = self.visit_compound_statement(node.orelse)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 254, in visit_compound_statement
    self.last_ret = self.visit(stmt)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 459, in visit_If
    cond = self.visit(node.test)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 771, in visit
    return super().visit(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/home/ysun23/anaconda/envs/flashatt/lib/python3.10/site-packages/triton/compiler.py", line 775, in generic_visit
    raise NotImplementedError("Unsupported node: {}".format(typename))
NotImplementedError: Unsupported node: BoolOp

Thank you so much for your help!

**Comment by jkobject** [comment]
got the same issue. the pre MLIR version of triton cannot work with the triton version of LayerNorm for now...

Do you think there is any simple solution to this?

**Comment by tridao** [comment]
You can try triton 2.1.0 or 2.2.0
