### ISSUE TITLE
How to install on remote supercomputing center? 2.1.2+cu121 OSError

### ISSUE THREAD

**Issue by fisher75** [Dao-AILab/flash-attention#920]
Hi guys, I'm using university-provided remote supercomputing resources, therefore I don't have any sudo rights.

I think this problem may have happened often before, so anyone could help me with this? Thanks a lot!

```
(llava) [LLaVA]$ pip install flash_attn
Collecting flash_attn
  Using cached flash_attn-2.5.7.tar.gz (2.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      /var/tmp/pbs.6790223.pbs101/pip-install-j0gq0b5k/flash-attn_110858c7cfc14b34b220e02513e44cf4/setup.py:78: UserWarning: flash_attn was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/var/tmp/pbs.6790223.pbs101/pip-install-j0gq0b5k/flash-attn_110858c7cfc14b34b220e02513e44cf4/setup.py", line 134, in <module>
          CUDAExtension(
        File "anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1203, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "anaconda3/envs/llava/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      
      
      torch.__version__  = 2.1.2+cu121
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by alfiy** [comment]
I have the same issue.

**Comment by jiangpinghuang** [comment]
Please try to install the flash-attention package by downloading the appropriate .whl file from the releases page at https://github.com/Dao-AILab/flash-attention/releases. It works for me.

**Comment by ElNino9495** [comment]
how were you able to resolve this?

**Comment by TongLiu-github** [comment]
Hi Haozhuang, I met the same problem when installing flash-attention. How did you solve this?

**Comment by gg22mm** [comment]
> 感觉这东西就是不支持12.1，11.8和12.2对应的release都有，很逆天。。
> 
> 感觉这东西就是不支持12.1，11.8和12.2对应的release都有，很逆天。。
> 
> > I have the same issue.我也有同样的问题。

是的，就算安装上也用不了~
