### ISSUE TITLE
ModuleNotFoundError: No module named 'flash_attn_2_cuda'

### ISSUE THREAD

**Issue by Hansyvea** [Dao-AILab/flash-attention#933]
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flash_attn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/githubRepo/flash-attention/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/xxx/githubRepo/flash-attention/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ModuleNotFoundError: No module named 'flash_attn_2_cuda'

env:
cuda_version:12.2
torch:2.1

Why would this happen?

**Comment by yqin-falling-stars** [comment]
hi bro! did you solve it?

**Comment by coderchem** [comment]
me too，did you solve it?

**Comment by rantianhua** [comment]
same error.

**Comment by saurabh-kataria** [comment]
still getting this error

**Comment by RandyLee16** [comment]
Has anyone tried this method： https://github.com/kijai/ComfyUI-Florence2/issues/23#issuecomment-2228375397
seems it work for me sometimes

**Comment by akkikiki** [comment]
This happened to me when setting it up on aarch64 machine, and solved by building it from source:

```
git clone https://github.com/Dao-AILab/flash-attention.git
cd flash-attention
FLASH_ATTENTION_SKIP_CUDA_BUILD=FALSE
python setup.py install
```
`FLASH_ATTENTION_SKIP_CUDA_BUILD=FALSE` was the key (else `flash_attn_2_cuda` will not installed)

**Comment by titaiwangms** [comment]
> FLASH_ATTENTION_SKIP_CUDA_BUILD=FALSE
> python setup.py install

This works for me!

**Comment by hartmark** [comment]
I tried adding **FLASH_ATTENTION_SKIP_CUDA_BUILD=FALSE**

but it didn't work for me on ROCm.

I have filed a new issue for this:
https://github.com/Dao-AILab/flash-attention/issues/1601

**Comment by naiveank** [comment]
> This happened to me when setting it up on aarch64 machine, and solved by building it from source:
> 
> ```
> git clone https://github.com/Dao-AILab/flash-attention.git
> cd flash-attention
> FLASH_ATTENTION_SKIP_CUDA_BUILD=FALSE
> python setup.py install
> ```
> 
> `FLASH_ATTENTION_SKIP_CUDA_BUILD=FALSE` was the key (else `flash_attn_2_cuda` will not be installed)

Hi

Do I need to run on system 32 or which folder or drive in windows 10? I don't have any knowledge of this
