### ISSUE TITLE
ImportError: /home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by zzc0208** [Dao-AILab/flash-attention#975]
I'm trying to use `text-generation-webui`  to load an AWQ model but I encountered this error:
```shell
Traceback (most recent call last):
  File "/home/linjl/text-generation-webui/modules/ui_model_menu.py", line 249, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "/home/linjl/text-generation-webui/modules/models.py", line 94, in load_model
    output = load_func_map[loader](model_name)
  File "/home/linjl/text-generation-webui/modules/models.py", line 293, in AutoAWQ_loader
    from awq import AutoAWQForCausalLM
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/models/__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/models/mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/models/base.py", line 46, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/quantize/quantizer.py", line 10, in <module>
    from awq.quantize.scale import apply_scale, apply_clip
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/quantize/scale.py", line 8, in <module>
    from transformers.models.llama.modeling_llama import LlamaRMSNorm
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 55, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
env:
```shell
python 3.10.13
torch 2.2.2+cu121
flash-attn-2.5.9.post1
```

**Comment by alan-aboudib-mc** [comment]
I have the same issue. Not resolved yet.

**Comment by rkuo2000** [comment]
flash-attn-2.5.8 works
(mine is python 3.10.14, torch 2.3.0, ubuntu 22.04.4 LTS)

**Comment by AlexYoung757** [comment]
i have same the issue.
python 3.8.10
torch 2.1.2+cu121
flash-attn-2.5.8

**Comment by rkuo2000** [comment]
> i have same the issue. python 3.8.10 torch 2.1.2+cu121 flash-attn-2.5.8

you will need to roll back flash-attn version, I remembered flash-attn was working with torch 2.1.2+cu121

**Comment by AlexYoung757** [comment]
which version may works

**Comment by rkuo2000** [comment]
> > > i have same the issue. python 3.8.10 torch 2.1.2+cu121 flash-attn-2.5.8
> > 
> > 
> > you will need to roll back flash-attn version, I remembered flash-attn was working with torch 2.1.2+cu121
> 
> i try 2.5.4, 2.5.6, 2.5.7 still not works

it was few weeks back, I dont remember the verison, keep rolling back till it works.
or go for torch 2.3.0

**Comment by AlexYoung757** [comment]
> > > > i have same the issue. python 3.8.10 torch 2.1.2+cu121 flash-attn-2.5.8
> > > 
> > > 
> > > you will need to roll back flash-attn version, I remembered flash-attn was working with torch 2.1.2+cu121
> > 
> > 
> > i try 2.5.4, 2.5.6, 2.5.7 still not works
> 
> it was few weeks back, I dont remember the verison, keep rolling back till it works. or go for torch 2.3.0

python 3.10  torch ==2.30 still not works

**Comment by rkuo2000** [comment]
> > > > > i have same the issue. python 3.8.10 torch 2.1.2+cu121 flash-attn-2.5.8
> > > > 
> > > > 
> > > > you will need to roll back flash-attn version, I remembered flash-attn was working with torch 2.1.2+cu121
> > > 
> > > 
> > > i try 2.5.4, 2.5.6, 2.5.7 still not works
> > 
> > 
> > it was few weeks back, I dont remember the verison, keep rolling back till it works. or go for torch 2.3.0
> 
> python 3.10 torch ==2.30 still not works

try
pip install flash-attn --no-build-isolation

**Comment by rkuo2000** [comment]
> > > > > > i have same the issue. python 3.8.10 torch 2.1.2+cu121 flash-attn-2.5.8
> > > > > 
> > > > > 
> > > > > you will need to roll back flash-attn version, I remembered flash-attn was working with torch 2.1.2+cu121
> > > > 
> > > > 
> > > > i try 2.5.4, 2.5.6, 2.5.7 still not works
> > > 
> > > 
> > > it was few weeks back, I dont remember the verison, keep rolling back till it works. or go for torch 2.3.0
> > 
> > 
> > python 3.10 torch ==2.30 still not works

pip uninstall flash-attn 
pip install flash-attn --no-build-isolation

**Comment by Queuecumber** [comment]
It looks like this is because the pytorch wheel on pypi uses cuda 12.1 but flash attention is compiled with cuda 12.2.  I don't even know where you would get a cuda 12.2 wheel for pytorch to work with this, but the only option would be to compile from source I think.

**Comment by AlexYoung757** [comment]
> It looks like this is because the pytorch wheel on pypi uses cuda 12.1 but flash attention is compiled with cuda 12.2. I don't even know where you would get a cuda 12.2 wheel for pytorch to work with this, but the only option would be to compile from source I think.

there is not have  a  cuda 12.2 wheel for pytorch

**Comment by AlexYoung757** [comment]
> pip uninstall flash-attn pip install flash-attn --no-build-isolation

i try whl to install , still can't

**Comment by AlexYoung757** [comment]
> I'm trying to use `text-generation-webui` to load an AWQ model but I encountered this error:
> 
> ```shell
> Traceback (most recent call last):
>   File "/home/linjl/text-generation-webui/modules/ui_model_menu.py", line 249, in load_model_wrapper
>     shared.model, shared.tokenizer = load_model(selected_model, loader)
>   File "/home/linjl/text-generation-webui/modules/models.py", line 94, in load_model
>     output = load_func_map[loader](model_name)
>   File "/home/linjl/text-generation-webui/modules/models.py", line 293, in AutoAWQ_loader
>     from awq import AutoAWQForCausalLM
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/__init__.py", line 2, in <module>
>     from awq.models.auto import AutoAWQForCausalLM
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/models/__init__.py", line 1, in <module>
>     from .mpt import MptAWQForCausalLM
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/models/mpt.py", line 1, in <module>
>     from .base import BaseAWQForCausalLM
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/models/base.py", line 46, in <module>
>     from awq.quantize.quantizer import AwqQuantizer
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/quantize/quantizer.py", line 10, in <module>
>     from awq.quantize.scale import apply_scale, apply_clip
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/awq/quantize/scale.py", line 8, in <module>
>     from transformers.models.llama.modeling_llama import LlamaRMSNorm
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 55, in <module>
>     from flash_attn import flash_attn_func, flash_attn_varlen_func
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
>     from flash_attn.flash_attn_interface import (
>   File "/home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
>     import flash_attn_2_cuda as flash_attn_cuda
> ImportError: /home/linjl/anaconda3/envs/sd/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
> ```
> 
> env:
> 
> ```shell
> python 3.10.13
> torch 2.2.2+cu121
> flash-attn-2.5.9.post1
> ```

i try flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl. it works
i guess  only  "abiFALSE" can use

**Comment by Sunshine700** [comment]
I have the same issue when i am using vllm.
Just uninstall flash-attn, it works.

$ pip3 list | grep flash
# flash-attn                        2.5.9.post1
$ pip3 uninstall flash-attn

**Comment by Sunshine700** [comment]
I have the same issue when i am using vllm.
Just uninstall flash-attn, it works.

pip3 list | grep flash
flash-attn                        2.5.9.post1
pip3 uninstall flash-attn

**Comment by zzc0208** [comment]
> I have the same issue when i am using vllm.
> Just uninstall flash-attn, it works.
> 
> pip3 list | grep flash
> flash-attn                        2.5.9.post1
> pip3 uninstall flash-attn

😂😂😂I still hope to solve this problem. Flash-attn can accelerate reasoning. Of course, xformers can also be used in vllm to accelerate

**Comment by aulaywang** [comment]
+1. `flash-attn=2.5.8` is unable to install.
My version:
```
CUDA 12.1
torch 2.3.0
python 3.10.14
```

**Comment by cxg2333** [comment]
+1 
My version:
```
CUDA 11.7
torch 2.0.1
python 3.9.18
```
help!

**Comment by Bellocccc** [comment]
Thanks. Python 3.9.19，cuda12.2，torch2.3.0 flash_attn==2.5.8, it works.

**Comment by AllenDun** [comment]
python3.9 cuda12.1 torch2.2, build the flash-attn from source, it did not work, same error

**Comment by montagetao** [comment]
> I have the same issue when i am using vllm. Just uninstall flash-attn, it works.
> 
> pip3 list | grep flash flash-attn 2.5.9.post1 pip3 uninstall flash-attn

its works for me, but i have to remove the flash attn from the python files

**Comment by jinwater88** [comment]
torch=2.4.0+cu118，flash_attn-2.6.2+cu118torch2.4cxx11abiTRUE-cp312-cp312-linux_x86_64.whl+python3.12
I have this problem too, have you solved it?

**Comment by billysx** [comment]
https://github.com/huggingface/open-r1/issues/684
just using `flash_attn==2.7.4.post1` released earlier this year.

**Comment by SturgeonYang** [comment]
I use flash_attn-2.6.0+cu122torch2.4cxx11abiFALSE-cp310-cp310-linux_x86_64.whl in Ubuntu 22.04. It works.
Python 3.10.14; torch2.4
